### ISSUE TITLE
Khali - API Fire Error pls help!

### ISSUE THREAD

**Issue by kukmun** [beefproject/beef#1062]
I try to set up beef in my khali machine, I've put in the correct ip in the config.yaml files
but when I launch ./beef I get 1 error message "API Fire Error: authentication failed in {:owner=>BeFF::Extensions::Metasploit::API::MetasploitHooks, :id=>20}.post_soft_load()"
so plz how can I fix it, I guess it's the only thing stopping me from using beef

**Comment by CorpOfHack** [comment]
I have same error( 
How I can fix this problem?
`[!] API Fire Error: authentication failed in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>10}.post_soft_load()`
I need to integrate BeeF witho MSF and you msf modules.

**Comment by Chenospf** [comment]
Default password path  /usr/share/beef-xss/extensions/metasploit/config.yaml
If you configure a password，try to restart msfconsole

**Comment by hipzz** [comment]
what is the mean of the id=>24?

**Comment by hipzz** [comment]
@kukmun

**Comment by bcoles** [comment]
@hipzz

`:id => 24` is the BeEF internal ID for the metasploit extension.

You're receiving the `API Fire Error` because your metasploit integration is misconfigured.

Unfortunately the error message isn't very descriptive.

Fortunately, the `msfrpc-client` dependency has recently been updated to include more verbose error messages.

Do a `git pull` to grab the latest version of BeEF, and `bundle install` to install the latest version of msfrpc-client. This will enable more descriptive error messages which should help troubleshooting the metasploit integration configuration.

**Comment by hipzz** [comment]
Thinks and I will try to do it！

Sent from Mail for Windows 10
