### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#1083]
Fix each of the following tests working and documented in wiki

beef$ rake -T
rake all          # Run all tests
rake automated    # Run automated tests (for Jenkins)
rake integration  # Run integration unit tests
rake msf          # Run MSF unit tests
rake quick        # Run quick tests
rake unit         # Run integration unit tests

**Comment by wadealcorn** [comment]
Anyone keen to fix the tests (or lead fixing them)?

**Comment by xntrik** [comment]
Okay, I've gotten the quick/default/unit working (just by tidying up those UTF-8 issues).

**Comment by antisnatchor** [comment]
Is this done?

**Comment by bcoles** [comment]
Not yet.

The tests are mostly passing (except on Windows). Metasploit tests are broken. Documentation is lacking.


### Suites

```bash
$ rake -T
rake all                  # Run all tests
rake automated            # Run automated tests (for Jenkins)
rake bundle_audit         # Run bundle-audit
rake bundle_audit:check   # Check gems for vulns using bundle-audit
rake bundle_audit:run     # Update vulns database and check gems using bundle-audit
rake bundle_audit:update  # Update bundle-audit database
rake integration          # Run integration unit tests
rake msf                  # Run MSF unit tests
rake quick                # Run quick tests
rake unit                 # Run integration unit tests

```

### Unit and Integration

Unit and Integration tests are passing in the default configuration with:

* Ruby 1.9.3-p551 on Kali 1.0.6 with RVM
* Ruby 2.1.5-p273 on Kali 1.0.6
* Ruby 2.1.5 on Debian 8.1 with RVM
* Ruby 2.1.5 on Fedora 19 with RVM
* Ruby 2.1.6 on Fedora 19 with RVM
* Ruby 2.1.6 on Kali 1.0.6
* Ruby 2.1.6 on Kali 1.0.6 with RVM
* Ruby 2.2.2 on Fedora 19 with RVM
* Ruby 2.2.2 on Kali 1.0.6 with RVM

Reportedly these tests are passing on Ruby 2.x on Mac OSX also.

Unit and Integration tests haven't worked on Windows for a while.

The following integration tests are failing:

* test/integration/tc_dns_rest.rb (#1010)

This suite is not included in the default test suites.

The following unit test cases are stubs:

* test/unit/core/tc_autorun.rb (#670)
* test/unit/core/tc_logger.rb
* test/unit/core/tc_obfuscation.rb (#588)
* test/unit/core/tc_social_engineering.rb (#584)
* test/unit/extensions/tc_event_logger.rb (#33)
* test/unit/extensions/tc_hooks.rb
* test/unit/extensions/tc_ipec_tunnel.rb (#586)
* test/unit/extensions/tc_proxy.rb (#30)
* test/unit/extensions/tc_requester.rb (#29)
* test/unit/extensions/tc_xssrays.rb (#578)


### Third-Party

Metasploit tests are failing.

```
12 tests, 8 assertions, 1 failures, 8 errors, 0 pendings, 0 omissions, 0 notifications
25% passed
```

Also it would probably make more sense to clone msf in '/var/tmp' rather than '/tmp'.

### Ruby 2.x

#1126 needs to be addressed.

### Bundler Audit

[bundler-audit](https://github.com/rubysec/bundler-audit) test cases have been added to check the Gemfile for vulnerable Ruby gems. These tests should be integrated into the `all` and `integration` test suites; perhaps as part of the `CheckEnvironment` tests.

These tests are failing due to the following reportedly vulnerable Ruby gems:

* rest-client 1.6.9
* rake 1.5.2

```bash
$ bundle exec rake bundle_audit
Updating ruby-advisory-db ...
From https://github.com/rubysec/ruby-advisory-db
 * branch            master     -> FETCH_HEAD
Already up-to-date.
ruby-advisory-db: 226 advisories
Name: rack
Version: 1.5.2
Advisory: CVE-2015-3225
Criticality: Unknown
URL: https://groups.google.com/forum/#!topic/ruby-security-ann/gcUbICUmKMc
Title: Potential Denial of Service Vulnerability in Rack
Solution: upgrade to >= 1.6.2, ~> 1.5.4, ~> 1.4.6

Name: rest-client
Version: 1.6.9
Advisory: CVE-2015-3448
Criticality: Unknown
URL: http://www.osvdb.org/show/osvdb/117461
Title: Rest-Client Gem for Ruby logs password information in plaintext
Solution: upgrade to >= 1.7.3

Name: rest-client
Version: 1.6.9
Advisory: CVE-2015-1820
Criticality: Unknown
URL: https://github.com/rest-client/rest-client/issues/369
Title: rubygem-rest-client: session fixation vulnerability via Set-Cookie headers in 30x redirection responses
Solution: upgrade to >= 1.8.0

Vulnerabilities found!
```

### Documentation

The wiki page is a little out of date https://github.com/beefproject/beef/wiki/BeEF-Testing

**Comment by jcrew99** [comment]
The Tests have been updated to Rspec and seem to be running for me, i get no issues with Kali, Centos 7 and Ubuntu. 
The DNS and webrtc seem to have commented portions that need to be worked out and is there any more that especially need to be done, i.e. metasploit? 
@wadealcorn  @passbe  what are your thoughts on this?
