### ISSUE TITLE
Implement Module Autorun Rule Engine

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#1086]
Implement a method to automatically execute a set of modules based on previous module results. 

Use a client-side rules engine for use with the module autorun. When a autorun rules engine is executed by the framework all instructions will be contained in a set of JS instructions that do not interact with the sever until 100% of the execution is complete.

The process is data driven.

Use the following BRE.

https://github.com/tdegrunt/jools

This issue is blocked on:
#672
#671
#670
#669
#668

The following needs to be taken into consideration:

How to use the database support for Autorun modules - there is an unused tab-value table.
How the module input and output works.
How the current autorun works.
How jools works.
How the framework polling works

**Comment by jcrew99** [comment]
This can be closed as ARE has been implemented.

**Comment by bcoles** [comment]
> This can be closed as ARE has been implemented.

The ARE is server-side. This requires the client-side module to be executed and pass the results back to the BeEF server, at which time BeEF determines the next action to take and sends the appropriate code back to the client. Rinse repeat. This is slow. The intention was to implement the chaining logic client-side.

While a good idea in theory, the use of jools was first raised more than 10 years ago in #668.

An empty jools stub was implemented in the hook (f622171eef7bf5c8d002a9e8bd0f6b2bc4472e2d, 6063e6246dc0b3d82ab636dcdcc6e5f09bbbfb5b) along with test cases (fcbd2516e66952fe231d816030862775b69bff3d) more than 10 years ago. It has never been used since.

The jools library has also received no updates since 2012. There's also an open bug report since 2012 - although the bug may be invalid. The author is presumably alive and was committing code as recently as 2022.

jools has been removed in #2790.
