### ISSUE TITLE
Bug in the module Fake Notification Bar of Social Engineering to Internet Explorer.

### ISSUE THREAD

**Issue by Nevnaur** [beefproject/beef#1093]
Hi guys

Yesterday I was trying the last version of Beef 0.4.6.0 Alpha and I detect a little bug in the module “Fake Notification Bar of Social Engineering”.

If I chose the same module Fake Notification Bar to Firefox or Chrome the configuration window show the option to specify the plugin URL, but if you chose this same module to Internet Explorer not appear the option to specify the plugin URL.

You can see it in this screenshot the module Fake Notification Bar to Internet Explorer.

![00](https://cloud.githubusercontent.com/assets/8579725/5702403/f80f9150-9a59-11e4-9358-3fe58dfd61a9.png)

And you can see too in the module Fake Notification Bar to Firefox and Chrome appears the option to specify the plugin URL.

![01](https://cloud.githubusercontent.com/assets/8579725/5702405/02f0fb5e-9a5a-11e4-8719-9feb584927f1.png)

![02](https://cloud.githubusercontent.com/assets/8579725/5702408/0b943c8a-9a5a-11e4-84a9-cc0d91fbea5a.png)

Thanks in advance

Cheers

**Comment by wadealcorn** [comment]
Thanks for reporting this bug!

**Comment by soh-cah-toa** [comment]
Good catch! I will take care of it this week.

**Comment by wadealcorn** [comment]
Thanks

**Comment by wadealcorn** [comment]
Have you had a chance @soh-cah-toa to look into this?

**Comment by antisnatchor** [comment]
This is expected behavior afaik. I was using this module together with Java Applets dropper modules, and it works pretty well.

**Comment by bcoles** [comment]
Yeah this is intentional. The fake notification bar is used in a few places.

Unfortunately providing optional arguments to BeEF modules in not intuitive, and this module is usually used without providing a URL. Perhaps a separate module could be written.

The reason is this is called `fake_notification_ie` is we originally had only this module, however fake Chrome and Firefox notification modules were added later. Providing a URL for these modules made sense, as these browsers allow installing extensions via notification bars, and were used to trick users into installing extensions in the user's browser.

The appropriate way to "fix" this issue would be to create a new module which allows the user to specify a URL in a similar style to the Firefox and Chrome modules, then rename `fake_notification_ie` to `fake_notification` or `fake_notification_bar` or something similar.

if someone is keen to implement this, note that  `fake_notification_ie` is used in other places within the code base (specifically, some ARE rules) and also throughout the wiki. Renaming the module also breaks backwards compatibility for users who have written scripts which leverage the RESTful API, however this is of less concern.

**Comment by bcoles** [comment]
This issue is now fixed.

* [x] The `fake_notification_ie` module presents an IE style notification bar. It allows users to specify a notification message and a URL to download when the notification bar is clicked.
* [x] The `fake_notification` module presents an IE style notification bar. It allows users to specify a notification message (including arbitrary HTML, such as hyperlinks links)
* [x] The ARE rules which made use of `fake_notification_ie` have been updated to make use of `fake_notification`
