### ISSUE TITLE
network extension does not work on HEAD

### ISSUE THREAD

**Issue by evoltech** [beefproject/beef#1129]
After proceeding from [the instructions](https://github.com/beefproject/beef/blob/master/INSTALL.txt#L74)

`````
root:/usr/local/beef# date
Sun Jun 28 20:21:00 EDT 2015
root@:/usr/local/beef# git branch
* master
root:/usr/local/beef# ./beef
/usr/local/beef/extensions/network/extension.rb:24:in `require': cannot load such file -- dm-serializer (LoadError)
        from /usr/local/beef/extensions/network/extension.rb:24:in `<top (required)>'
        from /usr/local/beef/core/extension.rb:36:in `require'
        from /usr/local/beef/core/extension.rb:36:in `load'
        from /usr/local/beef/core/extensions.rb:26:in `block in load'
        from /usr/local/beef/core/extensions.rb:25:in `each'
        from /usr/local/beef/core/extensions.rb:25:in `load'
        from ./beef:45:in `<main>'
`````

If I archive extensions/network, then beef starts as expected.

I have confirmed that dm-serializer is installed:
`````
root:/usr/local/beef# rvm list

rvm rubies

=> ruby-1.9.3-p484 [ x86_64 ]
   ruby-1.9.3-p547 [ x86_64 ]
 * ruby-2.1.6 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

root:/usr/local/beef# gem list|grep dm
dm-core (1.2.1)
dm-do-adapter (1.2.0)
dm-migrations (1.2.0)
dm-serializer (1.2.2)
dm-sqlite-adapter (1.2.0)
`````

**Comment by bcoles** [comment]
Hi @evoltech 

This error indicates Ruby cannot find the `dm-serializer` library.

`gem list` will list local system gems rather than the gems for your specified RVM install of Ruby.

You can list RVM gems with:
```bash
ls `rvm gemdir`/gems
```

If the gem is not installed, ensure you `rvm use` your intended version of Ruby before running `bundle install`

```bash
rvm use ruby-2.1.6
bundle install
```

Hopefully this should resolve your issue. I haven't been able to reproduce the error and the Network Extension loads on Kali Linux test systems:
* without RVM using Ruby 2.1.5; and
* with RVM using Ruby 1.9.3, 2.1.6, 2.2.2.

If this doesn't resolve your issue, and the gem is installed, it should be safe to comment out `require 'dm-serializer'` from `extensions/network/extension.rb:24` for testing purposes. The extension should still load.

**Comment by bcoles** [comment]
Did this work for you @evoltech ?

Make sure you `git pull` also
