### ISSUE TITLE
How to use BeEF with a VPN

### ISSUE THREAD

**Issue by vitogambino88** [beefproject/beef#1168]
I have tried running metasploit using a vpn assigned External IP (which happens to be static)  and  vpn opened port  successfully. Now, I'd like to know if I can do same with BeEF, as I am trying to integrate MSF into beef but confused about what IP I'd set in the config.yaml
Please need help

**Comment by bcoles** [comment]
Hi @vitogambino88

The 'callback_host' and 'callback_port' in './extensions/metasploit/config.yaml' should be the public IP/port for metasploit. This would be your VPN IP address.

You'll also need to configure BeEF for metasploit RPC so BeEF can communicate with metasploit. ('host'  'port'  'user'  'pass' , etc)

Hope this helps.

Similarly, if you're running BeEF locally behind NAT you'll need to configure a public IP address if you want to access it from the internet. You can do this with 'public' and 'public_port' in ./config.yaml. This is the IP address/port you will use for the hook. You'll also need to forward port 3000 from your router to BeEF.

Additionally, you'll also need to forward ports 61985 and 61986 from your router to BeEF if you want to use websockets instead of XHR for communicating with the hooked browser.

This may also help: https://github.com/beefproject/beef/wiki/Configuration
