### ISSUE TITLE
Metasploit extension uses SSLv3 ClientHello (rejected by msf); ignores TLSv1 config.yaml?

### ISSUE THREAD

**Issue by MiWCryptAnalytics** [beefproject/beef#1171]
Hi,

Been playing with beef-xss on Kali 2 - couldn't get msf integration working with TLS.
From pcaps it looks like ruby is sending an SSLv3 ClientHello, even though the ssl_version: 'TLSv1' is set in extensions/metasploit/config.yaml. Changing to TLSv1_2, SSLv3, etc made no difference.
The metasploit msgrpc listener sends a TCP RST after ACK'ing the SSLv3 ClientHello from beef.

An openssl s_client handshaking with a TLSv1.2 ClientHello established the TLS session.

I would guess this is to do with the deprecation of SSLv3. I also couldn't work out how to change the ClientHello version flags (or how deep this was configured within ruby).

Is there a way to get BeEF to send a TLSv1+ ClientHello? is this a limitation of ruby?

Installed is:
beef-xss 0.4.6.1-0kali2
ruby 1:2.1.5+deb8u1

Thank you
MiW

**Comment by antisnatchor** [comment]
The metasploit integration is pretty old code, I will look into it.

**Comment by bcoles** [comment]
Thanks @MiWCryptAnalytics 

I've reproduced - and believe I've fixed - this error when using Kali 2.0.

It seems specifying the `ssl_version` as `TLSv1` is malformed - it should be `TLS1`.

This issue should now be fixed, see: https://github.com/beefproject/beef/commit/b0bf1c0c215bae0a1065267b085a35d0d1af9039

**Comment by bcoles** [comment]
Sadly, it turns out I foolishly implemented the version syntax `TLSv1` in the extension config, likely based on the commit message from the msfrpc-client repo or a misplaced belief that `TLSv1` was the appropriate value inline with a consistent naming convention. The actual code change to msfrpc-client made use of `TLS1` syntax :(

Here's a timeline which may help if the problem persists or should you wish to investigate further:

* Dec 6, 2011, BeEF's Metasploit integration updated from xmlrpc to msgrpc and introduced ssl_version - `Updated to work with the new metasploit msgpack server `
* Oct 15, 2014, rapid7/msfrpc-client gem was updated - `Default to TLSv1, not SSLv3`.
* Oct 18, 2014, BeEF's Metasploit integration extension was updated - `Prefer TLSv1 over SSLv3` -  integration using `TLSv1` continued to work on my test systems, including an older version of Kali (1.0.6) and other flavors of Linux such as Debian, Fedora and Ubuntu.
* Aug 11, 2015, Kali 2.0 was released.
* Sep 15, 2015, BeEF's Metasploit integration using `TLSv1` reportedly does not work on Kali 2.0, as per #1171.
* Jan 2, 2016, BeEF's msfrpc-client gem requirement updated from version 1.0.1 to 1.0.3 - `Update Gemfile.lock`
* Jan 25, 2016, #1171 resolved - `Change Metasploit ssl_version from TLSv1 to TLS1`

**Comment by bcoles** [comment]
@MiWCryptAnalytics let me know if this doesn't fix your issue.

Closing this issue.
