### ISSUE TITLE
Firefox/Iceweasel extension that confuses BeEF Framework (IPFlood)

### ISSUE THREAD

**Issue by joaovarelas** [beefproject/beef#1181]
Dear BeEF developers,

I'm a Portuguese security researcher and I found that IP Addresses of zombies keep changing if the infected user uses IPFlood extension (http://ipflood.paulds.fr/) and is impossible to execute any kind of arbitrary command.
This is happening because BeEF assumes the real IP address is inside the following headers:

HTTP_X_FORWARDED_FOR 
HTTP_CLIENT_IP
HTTP_VIA

Thank you,
Best regards

**Comment by bcoles** [comment]
Hi joaovarelas

I believe this is due to trusting `request.ip` from Rack when BeEF is not running behind a reverse proxy.

Hooked browsers are usually referred to by their ID rather than IP address. I've been able to execute commands on Firefox with IPFlood installed. Is there specific functionality that's not working for you?

I noticed the admin web UI does not work in Firefox while using the IPFlood extension. This makes sense, as the admin session is tied to IP.

**Comment by joaovarelas** [comment]
Hello bcoles,

The IP of hooked browsers/targets which have IPFlood installed will change at every refresh requested by the hook.js, and it's impossible to access them trough the BeEF Framework. 

I will attach a simple GIF as example.

![Image of Hooked Browser running IPFlood](https://i.gyazo.com/2c0725312a1eeae415b4e7b8b4c949d3.gif)
