### ISSUE TITLE
Using HTTPS for UI and HTTP for Hook

### ISSUE THREAD

**Issue by JohnTet** [beefproject/beef#1188]
I have beef working fine on my webserver , I have enabled SSL, which means I can access the admin panel and hook via HTTPS, but I want to access Admin panel via HTTPS only and hook with HTTP , how is that possible ?

**Comment by antisnatchor** [comment]
It is not possible to do this by default just with BeEF.

What I suggest is that you use mod_proxy or equivalent proxy modules for your favourite web server, and have that in front of BeEF. I use this setup in production and it's trivial to then have BeEF just on HTTP and managing the HTTPS handshake in Apache rather than BeEF.
