### ISSUE TITLE
Forge Request, Browser SSL Error

### ISSUE THREAD

**Issue by Comancheroo** [beefproject/beef#1191]
Hello, I installed last Beef version. My domain supported SSL.(SignSec Certification Authority)

This error fixed old version but last version not fixed, problem continues.
Old fixed link > https://github.com/beefproject/beef/commit/bf0f59e5d0ad3aacf903b0dba74c63488677f280

 Beef is give to error in the browser.. Rider > Forge Request after.

Mixed Content: The page at 'https://xxx.com:3000/demos/basic.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxx.com:3000/demos/secret_page.html'. This request has been blocked; the content must be served over HTTPS.

config.yaml

    # HTTP server
    http:
        debug: false #Thin::Logging.debug, very verbose. Prints also full exception stack trace.
        host: "xxx.com"
        port: "3000"
---
        # Experimental HTTPS support for the hook / admin / all other Thin managed web services
        https:
            enable: true
            # In production environments, be sure to use a valid certificate signed for the value
            # used in beef.http.dns_host (the domain name of the server where you run BeEF)
            key: "xxx-k.pem"
            cert: "xxx-c.pem"

--

        # Prefer WebSockets over XHR-polling when possible.
        websocket:
            enable: true
            port: 61985 # WS: good success rate through proxies
            # Use encrypted 'WebSocketSecure'
            # NOTE: works only on HTTPS domains and with HTTPS support enabled in BeEF
            secure: true
            secure_port: 61986 # WSSecure
            ws_poll_timeout: 1000 # poll BeEF every second

**Comment by bcoles** [comment]
Thanks @Comancheroo 

The proxy should work, ie `curl -isk https://127.0.0.1:3000 --proxy http://127.0.0.1:6789`

This is a separate issue specific to the Forge Request functionality.

I think the most appropriate/intuitive solution would be to allow users to enable/disable SSL for the forged request. Adding a 'SSL' checkbox to the Forge Request tab should resolve this issue.

I'll fix this.

**Comment by bcoles** [comment]
Hi @Comancheroo 

This issue should now be resolved. The Forge Request tab now has a SSL option which specifies whether the request should make use of SSL (ie, `https://`)

Would you care to verify?

Fixes were applied in the following commits:

* e354ab804585bdcbb93a75bca9abd8154e4c8279
* 95abdf6781323902745f49cf5aa530dd2659ce28
* 10d79b9a715044010659b9236bc0d80a7293aacb

**Comment by Comancheroo** [comment]
Hello, this problem(https) fixed. But rider not working.
There are same domain, different path.

Force request (success)
GET /info.php HTTP/1.1
Host: localhost:80

Force request (unsuccess)
GET /login.php HTTP/1.1
Host: localhost:80
Response: Error! Could not retrieve the respons.

It's working after force request on browser but could not retrieve the respons on BeEF.
http://s29.postimg.org/l1ceu22kn/firefox_network.png

**Comment by bcoles** [comment]
Hi @Comancheroo 

Thanks for verifying the SSL issue is resolved. I'll close this issue.

Please open a new issue for the new issue you're experiencing.

Based on your screenshot the Rider/Requester should work and it looks like the hooked browser is Firefox. Unfortunately there's not really enough information to go on.

Is it just the login.php page that causes the issue? Can you browse other pages on the same domain:port? Is the Rider failing after requesting the `/info.php` page? Is the Rider failing after only one request? Is the Rider failing only for Firefox?

Also, `Response: Error! Could not retrieve the response.` is a generic statusbar error message returned to the BeEF web interface when the request appears to fail, which indicates only that the web interface was unable to handle the response, rather than an error with the Rider. Unfortunately that doesn't help much. Can you provide a screenshot of the relevant URLs in the Rider History tab?
