### ISSUE TITLE
Internal server Error with Beef

### ISSUE THREAD

**Issue by JohnTet** [beefproject/beef#1195]
I have been using BEEF and using it with sqlite.
I noticed that on client side all the requests are getting failed.

Here is the sample respnse

Request URL:http://127.0.0.1:3000/hook.js?BEEFHOOK=Qy5V2uGLgFy6LfKYS763TRluCX1xLYcLeP8GvUTc4xkPmuc4T8PuOp9HMMZL8T3NApBUOS12gQ77Z0E4&_=1452676303737
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:3000

It works fine untile I restart the PC, I know something could be wrong with the server configuration but I cannot see anything in apache /var/log/apache logs at all regarding this.

EDIT : I removed beef.db sqlite file and ran the beef process again , it worked fine.  Should I log errors in sql db instead sqlite ?

Question : Where do BEEF log all these requests that fails ? Does beef have a seperate log folder ?

**Comment by bcoles** [comment]
Unfortunately that error doesn't tell us much. It implies the BeEF server was unable to handle the request from the hooked browser, which is bad, but may simply be an issue with the configuration as you suggest.

Unfortunately BeEF does not log errors to a log file. You won't find errors in the Apache logs as BeEF does not use Apache. (Unless you're using Apache as a reverse proxy in front of the BeEF server).

If you set `debug: true` in `config.yaml` you'll get debugging output. If you then provide us with the error stack trace we can attempt to narrow down the cause. Additional information which will help us narrow down the cause of the issue is:

* Version of BeEF
* Version of Ruby
* Actions you were performing when the error occurred (running a module, using an extension, etc)
* Name and version of hooked browser

Regarding the database, have you updated BeEF recently? Generally, removing the BeEF SQLite database should not make a difference, however we occasionally make changes to BeEF data models which are incompatible with the existing database. It's unfortunate, and we try to avoid it, but that's the price of progress. If you want to clear the database, rather than delete the file you can simply run `./beef -x` which clears the existing database.
