### ISSUE TITLE
Issue with clone_page API

### ISSUE THREAD

**Issue by jllang320** [beefproject/beef#1208]
Using the following command...
`curl -H "Content-Type: application/json; charset=UTF-8" -d '{"url":"{TARGET_URL}", "mount”:"/news-room.aspx"}' -X POST http://{IPADDRESS}:3000/api/seng/clone_page?token={TOKEN};`

The server responses with the following message.
`[!] Invalid JSON input passed to endpoint /api/seng/clone_page`

My guess is it something simple but I can not figure it out for the life of me.

**Comment by bcoles** [comment]
Hi @jllang320 

Your command appears to have a malformed quote at `"mount”` - instead of `"mount"`

You may also need to specify `"use_existing"` and `"dns_spoof"` in your request. These are Boolean.

Take a look at the REST API examples which might help:
https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/clone_page
https://github.com/beefproject/beef/blob/master/tools/rest_api_examples/lib/beef_rest_api.rb#L366

**Comment by jllang320** [comment]
I know it was something simple, thanks..
