### ISSUE TITLE
port 3000 (for admin panel) immediately close after a connection

### ISSUE THREAD

**Issue by zen0x90** [beefproject/beef#1213]
Hi,

I have a strange behavior with beef. When I start it without shell enabled everything works fine. But when shell is enabled I can't connect to admin panel (port 3000).

However, the port remains open (netstat) until I don't attempt to connect to the admin panel. But, when I connect to  to the admin panel nothing happens and the port close itself.

Do you know how can I debug/fix it ?

**Comment by bcoles** [comment]
Hi @zen0x90

This issue is related to #1090

Unfortunately BeEF no longer supports Ruby < 2.0, and the console extension requires Ruby 2.0+.

**Comment by zen0x90** [comment]
Hi bcoles,

Thank you for your answer.

I'm sorry I forgot to give details about versions :
 ruby-2.2.3p173
 gem-2.4.5.1

I'm not using rvm but I can install it.

Do it exists a way to debug this ?

Regards

**Comment by bcoles** [comment]
The easiest way to fix this issue is by disabling the console extension with `beef.extensions.console.shell.enable: false` in `config.yaml`

Alternatively, if you really, really, really want to use the console extension, try using Ruby 1.9.3 and removing the Ruby version checks from `beef.rb` (there's only one or two). Unfortunately BeEF no longer supports Ruby < 2.0, so you're on your own here. If you would like to help fix this issue, issue #1090 is a good place to start.

**Comment by zen0x90** [comment]
I'm confused here. I'm using ruby version > 2.0. And you said beef no longer supports ruby < 2.0. So, I'm sorry again but why using ruby 1.9.3 (and remove the checks) to make it works ??

**Comment by bcoles** [comment]
The easiest way to fix this issue is by disabling the console extension with `beef.extensions.console.shell.enable: false` in `config.yaml`

**Comment by zen0x90** [comment]
Ok.

You should say the console is broken don't use it. Your solution is definitely not a fix. So I'm going to stick  with the web interface.

Thank you for your help.

**Comment by bcoles** [comment]
The console extension is broken don't use it.

If you do a `git pull` you'll notice an error message stating the same.
