### ISSUE TITLE
I've hooked a browser but i don't control it. Commands don't work.

### ISSUE THREAD

**Issue by haoskman** [beefproject/beef#1279]
when i try to execute get cookies command and other command, command text box is empty. I'm looking your videos. When command executed, data shows up in the command text area. in my computer don't show up. I'm using 0.4.6.1-alpha version.

![screenshot from 2016-07-14 01-28-32](https://cloud.githubusercontent.com/assets/19747645/16821998/537b1ce0-4962-11e6-89d4-5a77f0ec4a04.png)

**Comment by bcoles** [comment]
Hi @haoskman

The module you're executing is listed under the Chrome Extensions node of the command module tree. These modules work only when executed from within the privileged context of a Chrome browser extension. ie, you're executing JavaScript within an extension due to a XSS flaw, or you've coerced a user into installed a malicious extension.

Note the red icon for the selected module which indicates that the selected module is known to not work on the selected browser.

Also, you may want to consider updating your version of BeEF. The latest version is 0.4.7.0 which was released in December 2015.

**Comment by haoskman** [comment]
Hi @bcoles 
Thank you for reply, But all commands included(green button) are same. Any command in these list don't work. Besides how can i update my BeEF easily. Is there any document about updating BeEF ?
I'm using kali linux 2.0 Rolling. Thanks for information.

**Comment by bcoles** [comment]
Try cloning from GitHub.

```sh
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

**Comment by bcoles** [comment]
@haoskman did this work for you?

If not, do the modules under the `Debug` node of the command module tree work for you?

If not, what browser have you hooked?

**Comment by rajiv2790** [comment]
Hi @bcoles 

I am facing a similar issue. None of the commands seem to execute (including the debug ones). I am hooking a FireFox 48 on a Win7 x64 VM. I am using beef on a Kali x64 VM.

**Comment by bcoles** [comment]
Hi @rajiv2790 are you using the latest version of BeEF from GitHub? Are you running any anti-virus software on the hooked computer?

**Comment by rajiv2790** [comment]
Hi @bcoles,

I was currently using the updated version from Kali Linux repository. When I updated, the debug commands are working. However, the social engineering ones which are "Orange" are still showing me black results.

I do not have any AV

**Comment by bcoles** [comment]
@rajiv2790 what do you mean by black results?

Which modules are you trying? Some modules don't return results to BeEF until an event has occurred.

**Comment by rajiv2790** [comment]
@bcoles I meant blank results. Sorry for the typo. It is working now after pulling the latest branch.

**Comment by bcoles** [comment]
Thanks @rajiv2790

**Comment by Neymar8091** [comment]
I'm having the same issue and Ive tried updating beef but it just says that I need to install gem rainbow -v 2.2.1 and even when I do that command it just says this:

ERROR: Error installing rainbow:
ERROR: Failed to build gem native extension.

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext

/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1/gem_make.out


When I bundle install it comes up with this:


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext

/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/rainbow-2.2.1/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake
RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/rainbow-2.2.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/rainbow-2.2.1/gem_make.out

An error occurred while installing rainbow (2.2.1), and Bundler cannot continue.
Make sure that gem install rainbow -v '2.2.1' succeeds before bundling.

What do I do???

**Comment by bcoles** [comment]
Try `gem install rake`

**Comment by Neymar8091** [comment]
Thanks bcoles that worked but now im getting this error:

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.7.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/gem_make.out

An error occurred while installing nokogiri (1.7.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.7.1'` succeeds before bundling.

And again when I try to gem install nokogiri -v 1.7.1 it comes up with this:

Building native extensions.  This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.7.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20170626-2759-1c4ho48.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.7.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.7.1/gem_make.out

**Comment by bcoles** [comment]
Try `apt-get install ruby-libxml libxml2-dev libxslt-dev zlib1g-dev libsqlite3-dev`

**Comment by Neymar8091** [comment]
Thanks that worked

**Comment by Neymar8091** [comment]
Now everytime I start beef it comes up with this:

/usr/lib/ruby/2.3.0/psych.rb:474:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/data/geoip/country_code.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:68:in `<class:GeoIP>'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:58:in `<top (required)>'
	from /usr/share/beef-xss/core/loader.rb:21:in `require'
	from /usr/share/beef-xss/core/loader.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:25:in `<main>'
what do I do???

**Comment by bcoles** [comment]
Something like this:

https://github.com/tsu-iscd/beef-drive/issues/1

**Comment by Neymar8091** [comment]
Thanks but my commands still dont work even after updating beef

**Comment by bcoles** [comment]
@Neymar8091 please create a new issue and provide details

**Comment by Jeonamorh** [comment]
I’m also facing similar problems . I have also update beef but still no command is working including debug command.

**Comment by CalfCrusher** [comment]
the reason for that is 80% of beef-xss commands are not working anymore. Same for metasploit autopwn, they are all outdated, no working anymore. Nowadays hooking an up-to-date patched browser is simple, but in reality you can do very little

**Comment by Rourke101** [comment]
Same problem here. I am using the latest version (0.5.0.0) and hooked into a Chrome browser. Tried commands with the green ball, such as get cookies, and I never get anything at the "command results" screen
