### ISSUE TITLE
Questions about BeeF  over WAN

### ISSUE THREAD

**Issue by Amber234234** [beefproject/beef#1305]
a) I have seen some videos about using BeeF over WAN and they say the user must forward some ports, especifically : 3000, 5432, 80, 53 and 55552. Also,  the user's public ip must be placed on the "dns_host"  and "db_host" config.yaml fields.  
b) There are some fields called "public"(public ip I asume) and "public_port"(public forwarded port I asume) that are  unused which follow comentaries like #If running behind  a NAT.... and # port setting is experimental... 
My questions are:
¿Do I have to use both configurations a) and b) or just one of them?
On the #HTTP server block... does the field "port" must be the same as the one forwarded?
If ports aren't forwarded but config.yaml has been configured with public values, wouldn't the (public ip)(public port)/ui/panel should appear on the attacker's machine instead of the usual 127.0.0.1:3000/ui/panel?
  
Thanks!

**Comment by bcoles** [comment]
Hi @Amber234234 

It seems you may have been misled by the videos. This may help:
https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat

a.) You'll need to forward a port on the WAN interface to 3000/tcp on your BeEF box. Ports 61985/tcp and 61986/tcp must also be forwarded if web sockets are enabled for communicating with BeEF.

The "dns_host" config option is likely unrelated; as is the "db_host" config option which specifies the database hostname BeEF uses to connect to its database (only applies when MySQL/PostgreSQL is used).

Those other ports (5432, 80, 53 and 55552) do not need to be forwarded in the default configuration; however, forwarding ports 80 and 53 might make sense depending on your configuration.

Forwarding port 5432 is likely a bad idea as this will expose your PostgreSQL to the WAN. Likewise, forwarding port 55552 is also a bad idea unless you want to expose Metasploit RPC to the WAN interface.

b.) Yes you need to use both configurations. You'll need to forward ports to the host running BeEF to allow access to BeEF from the WAN. You'll also need to configure BeEF so that it knows it has a WAN interface in addition to the local network interfaces.

Yes, if config.yaml has been configured with `public` and `public_port` values, then (public):(public_port)/ui/panel should appear on the attacker's machine instead of the usual 127.0.0.1:3000/ui/panel

**Comment by bcoles** [comment]
Hi Amber234234 does this answer your question?

**Comment by Amber234234** [comment]
Sorry for the delay. The explanation is clear, but I can't prove it, since it seems my modem can't open ports. I have tested it for port forwarding with nmap and web-based tools and the ports appear as closed. 
Thanks!

**Comment by bcoles** [comment]
Hi @Amber234234 that's unfortunate. Most cheap SOHO grade routers will let you forward ports or have an alternate DMZ setting you can use.

It may also be your ISP. Some ISPs prevent access to specific ports on the WAN interface (such as SMB and ports commonly used by malware: 4444,1337,etc). You could try using non-standard or ephemeral ports.

Closing this issue.
