### ISSUE TITLE
Clarification for using beef over WAN

### ISSUE THREAD

**Issue by richerod** [beefproject/beef#1378]
Hi sorry for asking a similar question to ones asked before just having a bit of trouble getting beef working on a VPS server. Ive read a few tutorials but their info is conflicting, most of them say to edit dns_host, db_host and public IP and forward ports 3000, 5432, 55552, 53, 80. Ive tried numerous different configurations which leads me to believe its a port forwarding issue. When you say forward the ports do you mean "echo > 1 /proc/sys/net/ipv4/ip_forward" or add a specific rule to IPtables? and since im using a VPS where would i route the traffic from > to? My external to internal IP's? Lastly would i set my external ip in "Host Name / Domain Name" or "Reverse Proxy / NAT"
Thanks for taking the time to answer and I think beef is an excellent tool, great job guys :)

**Comment by bcoles** [comment]
Hi @richerod 

It depends on your VPS configuration. It's likely you don't need to forward ports unless your VPS is sitting behind NAT or a reverse proxy, rather than exposed directly to the internet.

Just make sure port 3000/tcp is allowed through the firewall. Ports 61985/tcp and 61986/tcp must also be allowed if web sockets are enabled for communicating with BeEF.

This should be sufficient to get BeEF up and running. The hook.js file should be accessing remotely. Try it.

If you can't access the hook.js remotely then review your firewall rules.

If you can access the hook file you're almost done. Simply ensure `beef.http.public` and `beef.http.public_port` are set to the public IP address and public port respectively and restart BeEF.

**Do not expose ports 5432 and 55552 to the internet.** These are PostgreSQL and Metasploit RPC.

**Comment by bcoles** [comment]
Hi @richerod

Using BeEF on WAN/VPS is straight forward.

You don't have to do anything in BeEF's configuration to get it up and running. The only changes required are for `beef.http.public` and `beef.http.public_port` but these are only client-side hacks for the hook so the JavaScript knows where to call home.

**Comment by bcoles** [comment]
Try running `nc -lvp 3000` on your VPS and connecting to it remotely. If you can't connect, review your firewall settings.

Then try running BeEF and port scanning port 3000 remotely. If the port isn't open, review your firewall settings.

**Comment by bcoles** [comment]
If port 3000 is open remotely, but you can't access the admin UI, try enabling `beef.debug` and `beef.http.debug` in `config.yaml` and see if you get any relevant output in the console.

**Comment by bcoles** [comment]
Note that it's incredibly unlikely that you will be able to access `127.0.0.1` or `192.168.1.131` remotely unless you're using VPN or SSH tunneling to the VPS. The former is the localhost interface and is not access remotely. The latter is RFC1918 address space and cannot be access remotely.

**Comment by bcoles** [comment]
Hi @richerod - how did you go with this?
