### ISSUE TITLE
Does recent Browser blocks the use of Java Payload

### ISSUE THREAD

**Issue by mohamedaminebelghith** [beefproject/beef#1406]
Hi , I don't know why Java Payload doesn't work for me . Are you sure that The module Java Payload can force browsers such (chrome/firefox...) to answer the request .?
I saw some forums that says : Recently , browsers blocks Beef Attack ? Is it true ?

**Comment by bcoles** [comment]
It depends on the Java security configuration rather than the browser configuration.

Java click-to-play was introduced a few years ago. In all modern versions of Java the user will be prompted to run the applet, or Java may block the applet entirely unless the Jar is signed with a valid and trusted certificate.

![Java warning](https://user-images.githubusercontent.com/434827/27624753-67cb31e0-5c25-11e7-9a16-6b271cca64d8.png)
