### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by hipzz** [beefproject/beef#1422]
API Fire Error: authentication failed in {:owner=>BeEF::Extension::Metasploit::API::MetasploitHooks, :id=>24}.post_soft_load()
-------------------------
with the kali server.
who knows the means of id=>24 ?

**Comment by bcoles** [comment]
`:id => 24` is the BeEF internal ID for the metasploit extension.

You're receiving the `API Fire Error` because your metasploit integration is misconfigured.

Unfortunately the error message isn't very descriptive.

Fortunately, the `msfrpc-client` dependency has recently been updated to include more verbose error messages.

Do a `git pull` to grab the latest version of BeEF, and `bundle install` to install the latest version of msfrpc-client. This will enable more descriptive error messages which should help troubleshooting the metasploit integration configuration.
