### ISSUE TITLE
Proposed project name change to TOFU

### ISSUE THREAD

**Issue by TomForager** [beefproject/beef#1443]
Our world is crumbling around us; CO2 emissions are causing glaciers to melt and temperatures to rise.

At the same time, the issue of animal cruelty and exploitation exists. Any life is as worthy of living as any other life, and for this reason a Vegetarian or Vegan way-of-life contributes toward the future well-being of the planet.

In addition to this, cows fart quite a lot, which contributes toward global warming as a whole. Thus, less cows to fart means a healthier planet.

Every time we deploy a beef hook, we contribute toward global CO2 emissions by introducing more farts to the atmosphere.

Tofu has proven itself to be a great alternative to beef, and does not fart. It's sustainable, easily-produced, and rather healthy. It's low in fat, high in protein, and does taste a little weird but you get used to it.

I propose renaming BEEF to TOFU in support of furthering efforts toward a better global state, reinforcing the stance toward animal rights, and lowering CO2 emissions as a whole.

This has the additional benefit of hooking TOFU into browsers around the world, increasing awareness of healthier alternatives, and lowering BEEF consumption considerably. A lower BEEF consumption means less cows, and thus less farts.

As a suggestion, TOFU may act as an acronym for The Online Fart Underminer.

I thank you for your consideration, and hope that we can move forward toward a better future.

**Comment by bcoles** [comment]
Hi @TomForager

The amount of energy required to change every instance of `beef` to `tofu` throughout the code base and associated documentation, in addition to the required name change and repackaging in all package management systems, in addition to the redistribution of the git history with the aforementioned changes for every clone of the repository, combined with the increased number of web searches performed by end users due to confusion over naming, the processing of HTTP redirects and processing overhead incurred by broken back-links, is likely to result in a net increase to energy consumption sufficiently larger than any perceived benefit; ultimately resulting in a change more detrimental to the environment than doing nothing at all.
