### ISSUE TITLE
Hooking not working

### ISSUE THREAD

**Issue by samofta** [beefproject/beef#1468]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?

0.4.7.0-alpha

On what version of Ruby?

ruby 2.3.3p222 (2016-11-21) [x86 64-linux-gnu]

On what browser?

Firefox - attacker
Google Chrome - victim

On what operating system?

Kali Linux 2 64-bit on an Oracle VM on macOS Sierra

#### Configuration

The config file has not been touched at all.

#### Summary

When I open the BEEF hook web address on another device on the same network, the browser tells me that the site cannot be reached. 

#### Expected Behaviour

I expected BEEF to hook the device and show it on the BEEF control panel.

#### Actual Behaviour

The device's web browser(Google Chrome on Android) tells me that the site(http://192.168.1.41:3000/hook.js) cannot be reached. 

#### Steps to Reproduce

1. cd into the `/usr/share/beef-xss` folder and do `./beef` 
2. Open a web browser and go to the beef panel
3. Try to hook a device.

#### Additional Information

None

**Comment by bcoles** [comment]
More information required.

**Comment by bcoles** [comment]
It sound more like a network issue, rather than an issue with BeEF.

Has BeEF opened port 3000? `lsof -i :3000`

Can you access the web interface from localhost? `curl -isk http://127.0.0.1:300/hook.js`

Are firewall rules preventing access to port 3000? `nc 192.168.1.41 3000 -v`

Can you access the web interface from the victim host? `curl -isk http://192.168.1.41:3000/hook.js`

Are both BeEF and the system on which the browser is running within the same subnet? (`192.168.1.0/24`)
