### ISSUE TITLE
X-Frame-Options header not set in Control Panel , Clickjacking vulnerability 

### ISSUE THREAD

**Issue by pehelwan** [beefproject/beef#1488]
Hey Beef Team,

I spotted that the Control Panel of the Beef XSS framework lacks any Frame protections that makes it susceptible to UI redressing and even sending vital information about the target including performing unintended actions .There's no SOP or Access control allow origin headers set in the control panel .

Pls roll out a patch or fix .

A CVE request for it has already been sent 

Regards,

**Comment by bcoles** [comment]
Yup, some parts of the admin UI extension don't use the `X-Frame-Options` header.

"sending vital information about the target" doesn't make sense.

Given that the admin UI component of BeEF does not accept URL parameters, there's no way to automatically populate any of the input fields. It would be incredibly difficult, if not impossible, to leak data to an attacker controlled URL.

At worst, an attacker could execute command modules on an individual zombie. It would be difficult and tedious to exploit this issue, requiring hijacking a minimum of 6 mouse clicks.

Here's a PoC:

`data:text/html,<iframe src="http://beef.local:3000/ui/panel" style="opacity: 0.1" width="1000px" height="1000px"></iframe>`

**Comment by pehelwan** [comment]
Well it has no Access-Control restrictions

**Comment by pehelwan** [comment]
I sent the PoC yet they want to demonstrate an impact . Yes there maybe some specially crafted XFS exploit that may get access to data on the client side , by simply adding an ajax request each time you scroll the page , the data from the parent elements of the page are sent to attacker's remote site

**Comment by pehelwan** [comment]
Here's a better PoC for all to understand where the prblm lies and I guess there's no security header anywhere - http://savanttools.com/test-frame/http://localhost:3000/ui/panel #

**Comment by pehelwan** [comment]
Obviously , Clickjacking ,XSS,CSRF may need some kind of User Interaction but aren't too difficult to execute as has been seen in past experiences

**Comment by bcoles** [comment]
This has been fixed in d1f114d103c03ae031c96f3f08014a3609c2e3cb.

Have you had any luck demonstrating impact? BeEF has some modules which may help.

The [iframe event logger module](https://github.com/beefproject/beef/tree/master/modules/misc/iframe_keylogger) successfully demonstrates stealing keystrokes from the admin UI. This is a viable attack, but it's worth noting that this attack would need to be launched from a third-party origin. A user who knowingly interacted with an instance of the BeEF admin UI which appeared out of nowhere, without checking he URL in the address bar, would likely also fall for a phishing page.

The [iframe sniffer module](https://github.com/beefproject/beef/tree/master/modules/misc/iframe_sniffer) demonstrates the attack you're talking about with exfiltrating information based on scroll events, aka leakyframe. However, the admin UI is scaled to full screen, and does not accept URL parameters, so I'd be interested if you can demonstrate a viable leakyframe attack.

The [clickjacking module](https://github.com/beefproject/beef/tree/master/modules/social_engineering/clickjacking) demonstrates crafting a clickjacking attack. However, a viable attack vector remains to be seen. A minimum of five sequential clicks in specific locations, without reloading the page, would be required to launch a command module with the module's default options. Even if this were possible, it would likely be low impact. It would be possible to clickjack the logout button, however this has very low impact.

**Comment by pehelwan** [comment]
Sending Vital Information -> That meant through XFS ,all that you have been explaining.

It certainly gives a great insight Brendan ,will you like to collaborate to write the exploit code ?

**Comment by bcoles** [comment]
Exploit code? The [iframe event logger module](https://github.com/beefproject/beef/tree/master/modules/misc/iframe_keylogger) successfully demonstrates stealing keystrokes from the admin UI.

**Comment by pehelwan** [comment]
Hey thanks and will it qualify for a CVE
Cheers !

**Comment by pehelwan** [comment]
Whatsup

**Comment by pehelwan** [comment]
? still not clear

**Comment by pehelwan** [comment]
ok

**Comment by bcoles** [comment]
You'll need to reach out to the BeEF developers. The security email address is `security [at] beefproject.com`.

iFrame event sniffing is a practical attack, albeit unlikely. The other attacks described above are impractical.

**Comment by bcoles** [comment]
Closing this issue as resolved.
