### ISSUE TITLE
[Bug] Pop Under Persistence Module Not Working

### ISSUE THREAD

**Issue by Tony874** [beefproject/beef#1495]
The pop under persistence module is now being blocked by default by most of the newest versions of all web browsers.

Also, it looks like this issue is related and may help the pop under persistence module https://github.com/beefproject/beef/issues/1486.

#### Environment

**What version/revision of BeEF are you using?** 
Newest 

**On what version of Ruby?**
Newest 

**On what browser?**
Chrome, Firefox and others

**On what operating system?**
Windows / Linux

**Comment by bcoles** [comment]
Popups have been blocked for the better part of a decade.

There are a couple of bypasses. The `Create Pop Under` module supports clickjacking. This requires minimal user interfaction (a click) to launch a popup.

The `Create Pop Under (IE)` module will bypass the popup blocker in almost all, if not all, versions of IE. This is probably patched in the latest IE11 and Edge, but I haven't checked.

**Comment by bcoles** [comment]
Other popup block bypasses exist, or have existed, often by abusing browser addons. There was one more recently which involved tricking Chrome's PDF reader.

These are typically worth $$$ and coveted by advertisers until the bug is killed. As such, it's rare that an 0day popup blocker bypass will appear in BeEF these days.

Then there's the issue of automatic updates in major browsers, or browser updates applied by operating system updates, which decrease the longevity of a bug - thus it's rarely worth the time investment to create a new BeEF module due to the short lifespan of the bug.

Of course there are exceptions, such as any browsers with a poor or non-existant update policy, such as those on some embedded or mobile devices, and IE on end-of-life systems or systems with OS updates turned off.

**Comment by bcoles** [comment]
As for #1486, similarly, it's hopeful-at-best.

There are several persistence modules to achieve short-lived persistence until the browser is closed. These can be found under the [Persistence](https://github.com/beefproject/beef/tree/master/modules/persistence) heading in the command module tree.

If you or someone you know has a browser 0day to achieve "persistent install" - which in most cases means remote code execution - you're welcome to give it to the BeEF project. That would be awesome!

These bugs are usually worth thousands if not tens of thousands of $$$ until the bug is killed. It's rare that a browser 0day RCE exploit will appear in BeEF.

**Comment by Tony874** [comment]
Yes, 0days would be unrealistic, although, I think this may be achieved by using the click jacking method like you suggested, to by bypass any ante pop up/ under protection.

Also, with the pop under window being hid under the time and date in the system tray for windows like demonstrated #1486 In the gif and using the confirm_close_tab module in the hidden pop under window.
