### ISSUE TITLE
Proxy history does not render if port is `null`

### ISSUE THREAD

**Issue by bvnmcbnmvc** [beefproject/beef#1498]
It seems BeEF's Tunneling feature doesn't support cross-domain requests. Are there any features in BeEF that would allow an attacker to proxy HTTP requests (from a hooked browser) and access the targets AP gateway (e.g. http://192.168.0.1)? @bcoles @wanton1950 

If not using BeEF, would you be able to recommend a way to achieve cross-domain requests from a hooked browser using another tool or method? Where's a good place to start exploring this subject?

**Comment by bcoles** [comment]
The tunneling features (requester aka rider, and proxy) sends cross-domain requests.

However, the response will not be returned to BeEF due to the same origin policy - unless the destination supports CORS and the requesting URI is whitelisted in the destination's CORS policy, in which case you can view the response.

As an aside, it looks like there's a bug in the Rider UI which prevents displaying the response if the port is `null`. As a work around, ensure you specify the port in the `Host` header when crafting a request via the Rider. I haven't tested the proxy - the issue may be present there too.

Alternatively, you can also use the `Debug -> Send CORS Request` command module to send CORS requests and view the response.

**Comment by bcoles** [comment]
Regarding accessing the gateway's web interface, you could use DNS rebinding as a method to bypass SOP. Be sure to use the target's WAN IP address rather than the LAN IP address, because reasons.

**Comment by bcoles** [comment]
This should be fixed in #1687.
