### ISSUE TITLE
Autorun = > Rider -> Get_Page_HTML

### ISSUE THREAD

**Issue by Comancheroo** [beefproject/beef#1512]
Hello,

I need to autorun for Rider.
Because, I can't always online the Beef panel.
I want to see the source of the other pages.
Get_Page_HTML good module but only works on current page..
I need more of this module for the other links(same origin).

For example;
x user, click on the site.com
I. source code = > site.com || possible with get_page_html module/autorun.
II.source code = > site.com/index2.php || impossible, it's only possible with Rider.
I need to autorun for Rider. Is this possible?

**Comment by Comancheroo** [comment]
Hello bcoles,

Thank you for your interest, test_cors_request module very useful. I didn't know that.
Could you create a sample autorun for test_cors_request?

**Comment by bcoles** [comment]
Cool. If you have a specific target host / URL, you could write your own command module (based on the cors module) with hard-coded targets URLs, and set that module to auto run. This would give you greater flexibility. For example, you could use data from the CORS request in subsequent requests.

I had intended to write a CORS spider module, but unfortunately that's not going to happen due to time constraints.

Closing this issue.
