### ISSUE TITLE
weather i can use beef over WAN via Ngrok or portmap.io free version only single port opened?

### ISSUE THREAD

**Issue by ArunDinfinity** [beefproject/beef#1596]
Weather i can use beef over WAN via Ngrok or portmap.io free version only single port opened?
I manage to work beef  in there servers but i failed to hook i think its cuz of the port problem , is there any way i can bypass this problem with single port(3000) opened ,When i try to open port in my router its not opening ,also i try to open all port via DMZ Host, but when i create that rule, my internet connection not working.......

**Comment by bcoles** [comment]
A few other users have used ngrok and managed to get it working. You might find some useful information in one of the issues:

* https://github.com/beefproject/beef/issues?utf8=%E2%9C%93&q=is%3Aissue+ngrok+

**Comment by azamet90** [comment]
> A few other users have used ngrok and managed to get it working. You might find some useful information in one of the issues:
> 
>     * https://github.com/beefproject/beef/issues?utf8=%E2%9C%93&q=is%3Aissue+ngrok+

pls ask to @HackerUniverse if him can have success with this information link... no one can understand this... i tryed all type of ways which can be posible (with reading this informations) but the explaining is very very short... since 2018 no one was able to write information detailed even with images much better...
