### ISSUE TITLE
Hooked browser not connecting to Beef

### ISSUE THREAD

**Issue by exander77** [beefproject/beef#1660]
Running 0.4.7.0-alpha from Github on ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]. The browser appears in Beef UI only when using the demo. I am using SSL with LE certificate. Hook loads fine into the page, I debugged part of the code so I know it is being processed, but the browser does not appear in Beef UI and no data seems to be sent to beef (no network connection XHR or other established).

What could be the issue?

**Comment by bcoles** [comment]
Thanks for the heads up and useful issue description.

Your use case should work.

Unfortunately, BeEF hasn't been tested thoroughly on Ruby 2.5 and not at all on 2.6 afaik.

Unfortunately due to limited development resources, you're probably on your own here.

I can suggest trying with `beef.debug: true` and `beef.http.debug: true` in `config.yaml`, and seeing if any errors show up in console.

Falling back to Ruby 2.5 *might* fix the issue.

It would also be useful to know whether the issue occurs when using clear text HTTP, rather than HTTPS.

**Comment by exander77** [comment]
Downgraded to Ruby 2.5.3, seems like no change, the only related thing to hooking is:
JQMIGRATE: Migrate is installed with logging active, version 1.4.1
In the console as was before.

Will try debug. Seems like the problem with the hook. No contact with the Beef from the browser, no network connections.

**Comment by bcoles** [comment]
You can also enable `beef.client_debug: true` in `config.yaml` to enable client debugging in the browser console.

**Comment by bcoles** [comment]
Any luck with this?

**Comment by AdriBloober** [comment]
I have the same problem.
