### ISSUE TITLE
Review DataMapper dependency

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#1685]
Review the use of DataMapper and consider alternatives, such as ActiveRecord.

DataMapper hasn't released a new version since 2013. Changes have been made to the [DataMapper GitHub repository](https://github.com/datamapper/dm-core/) as recently as 2016, however a new version of the Gem has not been published.

**Comment by elbowdonkey** [comment]
In theory, it wouldn't be too difficult to use ActiveRecord instead of DataMapper.

I've actually done that on a fork, though I'm not yet sure if I have full functionality. For reasons unknown so far, new hooked browser records aren't being saved. I suspect that might be unrelated to using ActiveRecord though.

I'll work on a formal PR that swaps ActiveRecord for DataMapper once I've done so more testing.

For those curious, the way to do the swap goes like this:

# Setup

- remove all DM related gems from Gemfile
- add ActiveRecord to to Gemfile
- add `sqlite` or `pg` gems as needed to Gemfile
- adjust `core/loader.rb` to require `active_record`, remove all DM requires
- enable ActiveRecord (as well as migrations, database configs, etc) using something like the `otr-activerecord` Gem (or similar)
- make sure db and migration tasks are available to Rake
- make sure nothing references anything datamapper related

# The tedious part

You can either "shim" the old Datamapper models, so that things like `ModelName.first(:lastseen.gte => date)` just work somehow. I didn't go this route because if we're swapping out Datamapper, we should just really swap it out. That means:

- remove all instances of `include DataMapper::Resource`
- anything that used to do `include DataMapper::Resource` needs to now inherit from `ActiveRecord::Base`
- remove all `storage_names[:default]` references (let ActiveRecord use its own conventions for table naming)
- adjust any calls to Datamapper specific methods to work using ActiveRecord's query api. so `ModelName.first(:lastseen.gte => date)` becomes `ModelName.where(['lastseen >= ?', date]).first`, and `ModelName.all(:session_id => id)` becomes `ModelName.find_by(session_id: id)`, and so on. There maybe 30-60 uses of the old Datamapper syntax.
- examine each Datamapper model class's property list. Use them to create a huge migration

I'm sure I'm missing stuff, but that's basically how I ended up getting stuff to at least not throw exceptions. It goes without saying that the old database is totally destroyed. This isn't an "upgrade" as much as it is a new install.

**Comment by jcrew99** [comment]
Hi @elbowdonkey, I was going to pick this up. It's really cool that you're able to make this change and that if the tests pass would you consider pushing the changes to master?

**Comment by jcrew99** [comment]
@elbowdonkey  If there is anything that we can do to help you make those changes please let us know, if there is any more of the tedious work to be done, i will be happy to take it on

**Comment by elbowdonkey** [comment]
I think I've just now got most of it working with ActiveRecord, using Postgres as the database. I've been able to hook browsers and run a few simple host commands (alerts, HREF rewriting, etc).

My ultimate goal is to be able to host it on Heroku, which is what motivated the change to ActiveRecord in the first place (the `bytea` datatype seems to be problematic there?).

Next steps for me are to see if it'll work on Heroku now. If it works there, it's likely to work anywhere. If it doesn't, I'll continue on to the "final" step anyways:

Do a diff between my fork and `master`, see what changed, and submit a PR that's cleaner than my fork. I sprinkled notes, logs, pry's, all throughout that can be thrown away now. Might as well just do that as part of a new PR.

Also, I have no idea if unit tests work. Never did run them. So that'll need help too.

**Comment by elbowdonkey** [comment]
This may never run properly on Heroku as written, and may only partially work elsewhere.

Locally, I can hook browsers, but they bounce around between Online and Offline, and don't consistently run simple commands (like an alert). I'm not sure why that happens, but I suspect it has to do with porting from Datamapper to ActiveRecord. There are just too many places where the old code does things entirely different that the conventions found in ActiveRecord. Add to the mix the fact there are multiple implementations for how hooked browsers are created, browser details, and so on. It's a bit gnarly.

When deployed to Heroku, no new hooked browsers are ever created. The place where a hooked browser is saved to the database never even executes. I've wrestled with it for hours now, and I think what it boils down to is weirdness with `EventMachine` and with how Heroku handles threads.

I'm honestly thinking it's not effective to try a simple port from Datamapper to ActiveRecord. Ideally, the concept of the project itself should be replicated in something using modern Ruby and Rails best practices, where the different facets of the original project possibly even standalone applications (a Rails API app for the rest API, a conventional Rails app for the admin, a simple websocket service app for websockets, and so on).

I truly wish a simple port just worked, but it doesn't.

**Comment by JessW98** [comment]
Closing ticket because this is all done :)
