### ISSUE TITLE
Check ruby version before installing `ruby-dev`

### ISSUE THREAD

**Issue by sidahmed-malaoui** [beefproject/beef#1704]
I have a proposition rather than a real issue.

I have Ubuntu 16.04 and I used `snap` to install `ruby 2.6.1`. When beef install process is launched ( `./install`), it installs `ruby-dev` which will install `ruby2.3`. When checking ruby installed version, it will find `ruby2.3` instead of `ruby2.6.1` (because of the path priority). So `./install` will quit after showing this : 

>[FATAL]  Ruby version 2.3.1 is not supported. Please install Ruby 2.4 (or newer) and restart the installer.

Even if we add the repository `ppa:brightbox/ruby-ng` and install `ruby2.5-dev`, the installation process will fail.

So I think it would be better to check ruby installed version before installing `ruby-dev` package.

PS : `beef` rocks.

**Comment by bcoles** [comment]
Thanks for the report.

Ruby 2.3 is EOL in a couple weeks, at which point hopefully the `ruby-dev` package no longer requires `2.3.1`.

I agree its an issue, but I don't have a simple solution for this, as it's effectively an environment issue.

Hopefully this situation will sort itself out in the next couple weeks.

> When checking ruby installed version, it will find `ruby2.3` instead of `ruby2.6.1` (because of the path priority)

Presumably your system Ruby (ie, `which ruby`) points to a `2.3` install, in which case BeEF will likely fail to run when you `./beef`, and other parts of the installer will also fail (ie, gems will probably be installed for 2.3 rather than 2.6).

The `check_ruby_version` function uses `ruby${RUBYSUFFIX}` as the Ruby executable. `RUBYSUFFIX` should be `''` on Linux systems, as it only gets defined on `FreeBSD` and `OpenBSD` platforms.

Moving the Ruby version check before the OS check will likely introduce other issues (ie, the OS check will install packages, which in your situation will apparently install Ruby `2.3`, causing issues elsewhere).

Moving the `ruby-dev` (aka `ruby-devel`) install into a separate function is a possibility. Maybe performing the version check before and after the OS check would also work. Or perhaps `/usr/bin/env ruby` should be used.

I'd prefer not to rework the installer due to the large amount of testing involved. It's a time sink and dev efforts are better spent elsewhere, but pull requests are always welcomed.

As a workaround, manually installing is fairly straight forward. In short: install Ruby, install OS packages, install `rubygems`, `gem install bundler`, `bundle install  --without test development`.

Alternatively, you could comment out the version check and hope for the best, although this will likely result in the required gems being installed for Ruby 2.3 not 2.6.

Another solution is to use a Ruby environment manager such as `rbenv` or `rvm`. I used these extensively up until Ruby 2.5 and it worked pretty well.

If you're like to learn more about the install process, and the decisions which lead to where we are now, you can find some history here: https://github.com/beefproject/beef/issues/1477

**Comment by z7701858** [comment]
I have the same problem as you.
My solution:
use rvm to setup ruby2.6
and use
 `rvm use 2.6.0 -- default` 
to set the default version
then
```
gem install bundler

git clone git://github.com/beefproject/beef.git

cd beef

./install

./beef
```

**Comment by jackdwalker** [comment]
@jcrew99 @DeezyE - this is solved in #1940 correct? I think this can be closed off after taking a cursory look at the code + issue described here.

**Comment by Ax125** [comment]
@jackdwalker the update specifically looks at whether the user has a ruby package manager installed and checks ruby against that. While not specifically addressing the user's issue, the fact that it will now check if a ruby package manager is installed first means that  it is a simple fix - use rvm and it should all work fine.
I'm happy with close off.

**Comment by DeezyE** [comment]
@jackdwalker the update specifically looks at whether the user has a ruby package manager installed and checks ruby against that. While not specifically addressing the user's issue, the fact that it will now check if a ruby package manager is installed first means that it is a simple fix - use rvm and it should all work fine.
I'm happy with close off.
