### ISSUE TITLE
[Question]Making BeEF persistent.

### ISSUE THREAD

**Issue by samd10** [beefproject/beef#1734]
Is there a practical way to make beef hooked to the target browser even if the target user closes the hooked webpage.Link to a website or youtube video will be appreciated.
[Thanks for your time]

**Comment by bcoles** [comment]
There are some [persistence modules](https://github.com/beefproject/beef/tree/master/modules/persistence) for persistence.

In particular, the [Create Pop Under](https://github.com/beefproject/beef/tree/master/modules/persistence/popunder_window) and [Create Pop Under (IE)](https://github.com/beefproject/beef/tree/master/modules/persistence/popunder_window_ie) will create a popup window which contains the BeEF hook. The former will usually be blocked by the builtin popup blocker, unless specifically allowed by the user. The latter only works on IE, and exploits a flaw to bypass the popup blocker, however the flaw has since been patched.

The [Hijack Opener Window](https://github.com/beefproject/beef/tree/master/modules/persistence/hijack_opener) module uses `window.location.opener` to redirect the opening tab (not the hooked tab) to an arbitrary page which may contain a BeEF hook.
