### ISSUE TITLE
Information leakage

### ISSUE THREAD

**Issue by 9tail123** [beefproject/beef#1781]
![1](https://user-images.githubusercontent.com/35592183/66933951-5bdf3600-f06c-11e9-8160-42e6ffcbd2dc.png)
Wafwafwafwaf2019lib is my modified background address, but the Apache test page of the home page leaked it.

**Comment by jcrew99** [comment]
@9tail123  May you be able to provide more information as to your environment, the setup and the test?

**Comment by jcrew99** [comment]
Not sure where to go with this, closing as inactive

**Comment by bcoles** [comment]
> 
> 
> @9tail123 May you be able to provide more information as to your environment, the setup and the test?

The issue is that the BeEF `admin_ui.base_path` UI admin panel path is "leaked" by the landing page when `web_server_imitation` is enabled. This undermines web server immitation.

This would be resolved by fully decoupling the admin UI from the hook server, and ensuring that the assets associated with `web_server_imitation` are stored in a different directory to the admin UI assets.

* #1389
* #1391

Ideally, the appropriate web server imitation URL routes would be configured in the same manner as the imitated server. ie, if Apache has a `/path/to/some/banner.png` in the default HTML, the associated route should be configured on the server, with the appropriate `banner.png` mounted at this route.
