### ISSUE TITLE
Hook url cant connect outside my lan therefore beef is not working on ngrok

### ISSUE THREAD

**Issue by Rigboat27** [beefproject/beef#1801]
#### Environment

What version/revision of BeEF are you using? Browser Exploitation Framework (BeEF) 0.4.7.4-alpha-pre

On what version of Ruby? (1:2.5.2)

On what browser? Firefox

On what operating system? Kali Linux

#### Configuration

Are you using a non-default configuration? No

Have you enabled or disabled any BeEF extensions? No

#### Summary
I am using ngrok for tunneling outside my lan so i can use beef on the internet.
when i access my hooked website on another device, the device cant get back to the main beef console in order for it to start showing me that the browser is hooked.
Pls help
Please provide a summary of the issue.

#### Expected Behaviour
It should have got back to hook page of beef to start working
What was the expected result?

#### Actual Behaviour
The device could not reach the hooking page of beef 
What was the actual result?

#### Steps to Reproduce
Insert JS code into website
Use ngrok to get it on the internet
visit this site
annd Volia!
Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by azamet90** [comment]
> #### Environment
> 
> What version/revision of BeEF are you using? Browser Exploitation Framework (BeEF) 0.4.7.4-alpha-pre
> 
> On what version of Ruby? (1:2.5.2)
> 
> On what browser? Firefox
> 
> On what operating system? Kali Linux
> #### Configuration
> 
> Are you using a non-default configuration? No
> 
> Have you enabled or disabled any BeEF extensions? No
> #### Summary
> 
> I am using ngrok for tunneling outside my lan so i can use beef on the internet.
> when i access my hooked website on another device, the device cant get back to the main beef console in order for it to start showing me that the browser is hooked.
> Pls help
> Please provide a summary of the issue.
> #### Expected Behaviour
> 
> It should have got back to hook page of beef to start working
> What was the expected result?
> #### Actual Behaviour
> 
> The device could not reach the hooking page of beef
> What was the actual result?
> #### Steps to Reproduce
> 
> Insert JS code into website
> Use ngrok to get it on the internet
> visit this site
> annd Volia!
> Please provide steps to reproduce this issue.
> #### Additional Information
> 
> Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

did u fix that problem? i want to do it without using beef over wan because of it is working only on apache hosted localhost place

**Comment by Rigboat27** [comment]
Nope, still didn't fix the issue
I didn't understand the last part, could you explain clearly
I haven't used it in a while
I will try later

**Comment by azamet90** [comment]
there is one tool named "Beef Over Wan" but it is working part of only about doing it with ngrok with the information of beef-xss wiki page i do not have success because of they not explain anything... and im not sure if they did tryed it themself :D @bcoles maybe can help us i hope

**Comment by Rigboat27** [comment]
Yeah
I will check everything again and inform you if there are issues
I also didn't portforward last time because I was locked out of my router settings
Now I can
I will research and try to make it work now
Stay active on this post

**Comment by Rigboat27** [comment]
Oh
It should work without beef over wan
Wait I'll check and tell within 24hrs

**Comment by azamet90** [comment]
> Oh
> It should work without beef over wan
> Wait I'll check and tell within 24hrs

the point of beef over wan is as u know for those people who not have wlan but using mobile hotspot for example...
i hate that tool because of it is not working completely... only one index.html page...
i still want to use that tool with ngrok, serveo.net or portmap.io not important which one but not that tool named "beef over wan". 
in google, youtube or anywhere is not posible to find any information about that and the wiki of beef-xss is not explaining exactly how to do it...
thx for giving time to me ... if this is posible to do it with any tunneling site for u i want to know it how u did it...

**Comment by flavius411** [comment]
I've got the same problem, have you guys solved it?

**Comment by Rigboat27** [comment]
The thing is, i think, there needs to be two ngrok URLs, one for the victim, and one for beef to listen on WAN. So i tried using BeefOverWan itself, and did everything successfully. But at the end, when i try to login to the admin panel over WAN, i press enter, and just get reloaded back onto the same page, while on the beef console, it shows me that my WAN ip has logged into the admin panel. But the hook page loads fine, it needs sudo to make the page onto the local html dir tho.

**Comment by bcoles** [comment]
> 
> 
> there is one tool named "Beef Over Wan" but it is working part of only about doing it with ngrok with the information of beef-xss wiki page i do not have success because of they not explain anything... and im not sure if they did tryed it themself :D @bcoles maybe can help us i hope

Beef Over Wan is an unoffical tool.

BeEF hasn't been tested thoroughly with ngrok and HTTPS as HTTPS support requires a paid account.

Working with someone who had a paid account revealed that there is an issue where there's a discrepancy between BeEF using HTTPS and the `public` host using HTTPS.

You'll run into issues if you're using ngrok with a HTTPS URL and BeEF is not using HTTPS.

It's been a while since I looked at it, but if I remember correctly there's a couple of solutions to allowing using BeEF with nkgrok+HTTPS.

One solution is to run BeEF with HTTPS by setting `enabled: true` in the `config.yaml` file:

https://github.com/beefproject/beef/blob/845b2db2555082e6a645160a2a7ed807df063b03/config.yaml#L90-L91

Or, as a workaround, patch the protocol to "https" in `beef/core/main/client/net.js` :

https://github.com/beefproject/beef/blob/845b2db2555082e6a645160a2a7ed807df063b03/core/main/client/net.js#L24

Both solutions require configuring the `public_*` settings correctly as you would normally. You will need to ensure that the `public_host` reflects your ngrok address, and `public_port` reflects the HTTPS port of the ngrok service (presumably `443`).

**Comment by bcoles** [comment]
There's an open issue (#1785) describing the issues with the current implementation. It is a large piece of work and despite being labeled as "critical" there's no appetite to fix it.

The current approach works, but it's a bit of a mess, and leads to confusion which stems from a fundamental misunderstanding of network routing.

When BeEF starts up, it will listen on all network interfaces by default. Unless you're operating a public server on the Internet, the network interfaces all have IP addresses on their associated local network. It is impossible for remote clients outside of the LAN to connect to these IP addresses as they are not routable from outside the LAN.

BeEF has no way of automatically knowing what its public IP address is. ie, access to BeEF may be via port forwarding on the border gateway or from a frontend reverse proxy. As such, the generated `hook.js` code does not know what IP address should be used for remote command and control. By default, one of the network interface IP addresses is used.

To solve this issue, the `config.yaml` file allows users to specify a "public" hostname and IP address (`public_host` and `public_port` respectively). These values are then used in the JavaScript code used for command and control so that the JavaScript code running on the client can connect to the correct routable public host.

This results in a few issues, such as only allowing one public host address. This can be resolved by running multiple instances of BeEF for different campaigns, but obviously that's not idea.

Secondly, as described above, there are issues when one of BeEF or the public server are using HTTPS and the other isn't. Even though the hostname and IP address are correct, the URL scheme (`http` / `https`) may be incorrect.

**Comment by Warhammar** [comment]
Having the same issue.. and BeefOverWan is not my solution..

**Comment by bcoles** [comment]
> But at the end, when i try to login to the admin panel over WAN, i press enter, and just get reloaded back onto the same page, while on the beef console, it shows me that my WAN ip has logged into the admin panel.

This is a known issue tracked here #2527. As a workaround, you can login to the admin panel using one of the local network interfaces instead of via the ngrok URL.

**Comment by bcoles** [comment]
> Having the same issue.. and BeefOverWan is not my solution..

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/Using-BeEF-With-NGROK
