### ISSUE TITLE
"The site ahead contains harmful programs"

### ISSUE THREAD

**Issue by goldingdamien** [beefproject/beef#1802]
I am getting the red Google warning screen with "The site ahead contains harmful programs" when visiting "https://github.com/beefproject/beef". What is the issue?

**Comment by jcrew99** [comment]
@goldingdamien  Beef was marked as containing malware. We have tried contacting Google, but they need us to prove that we own it(which we can't since we don't own Github) and github have said they are unable to influence google from their end. We tried using Google's verification method but it didnt work. We have another issue open for this so i am going to close this as duplicate.

**Comment by larsonreever** [comment]
i would like to share a reference here, actually i also got the same issue so thought to share my findings here, this article here really helped me DIY and resolve the issue on my wordpress site. https://secure.wphackedhelp.com/blog/the-site-ahead-contains-harmful-programs/
