### ISSUE TITLE
beef on windows

### ISSUE THREAD

**Issue by Robin6464** [beefproject/beef#1803]
latest beef version fully works on windows in cygwin :)

1. install cygwin with all dependencies for beef from cygwin repo
2. install all gems (only nokogiri not install from repo rubygems)
3. in gemfile set nokogiri 1.10.3 installed from cygwin repo
4. install node-v12.13.1-x64.exe
5. in config.yaml set password different than beef
6. run beef in cygwin console

I tested a few modules and everything worked fine, I certainly haven't tested everything so something may not work :)

it can be helpful for people who do not want to run kali linux on a virtual machine and for their convenience run beef on windows

integration of beef with metasploit:

1. install latest framework metasploit for windows
2. in config.yaml files in beef set true for metasploit
3. run msfconsole and type: load msgrpc ServerHost=127.0.0.1 Pass=abc123 User=msf SSL=y ServerPor=55552
4. run beef in cygwin console

**Comment by jcrew99** [comment]
@Robin6464 I will test this myself and if it works, add it to the wiki. This would be cool to have Beef run in Windows, nice work!

**Comment by Robin6464** [comment]
I hope I did not mistake anything and your tests will be good, for curious I took screenshots of how it looks with me

https://imgur.com/a/wkIawYk

**Comment by jcrew99** [comment]
@Robin6464  I had random trouble getting it to load? Can you give a bit more info for a branch so we can try and put this wiki page together?

**Comment by Robin6464** [comment]
do you want to give more detailed information about running beef in cygwin?

**Comment by Robin6464** [comment]
I tested my installation only on version 0.4.7.4 but the following steps should work for each version.
Cygwin should have all the basic packages installed, such as ssl, wget libraries etc. I will not mention all this and I assume that the basic packages are already installed in Cygwin.
I have installed ruby 2.6.4p104 in my cygwin. I did not do "./install" and "bundle install" because the default installation of byebug and nokogiri will fail. I installed byebug 11.0.1 and nokogiri 1.10.3 from the cygwin repository. In the cygwin I installed manually ("gem install ...") every ruby from the gemfile file except nokogiri. In addition, I changed the version of nokogiri in gemfile from 1.10.4 to 1.10.3. Then I installed node-v12.13.1-x64 in windows and after installation it is recognized in cygwin. Finally, I changed the default password in the config.yaml file. That's all and now you should run beef.

**Comment by Robin6464** [comment]
beef-beef-0.4.7.4:

ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-cygwin]

nodejs v12.13.1

Using rake 13.0.1
Using public_suffix 4.0.1
Using addressable 2.7.0
Using ansi 1.5.0
Using io-like 0.3.0
Using archive-zip 0.12.0
Using buftok 0.2.0
Using bundler 1.17.3
Using byebug 11.0.1
Using mini_mime 1.0.2
Using nokogiri 1.10.3
Using rack 2.0.8
Using rack-test 1.1.0
Using regexp_parser 1.6.0
Using xpath 3.2.0
Using capybara 3.29.0
Using childprocess 3.0.0
Using chunky_png 1.3.11
Using curb 0.9.10
Using daemons 1.3.1
Using data_objects 0.10.17
Using diff-lcs 1.3
Using dm-core 1.2.1
Using dm-do-adapter 1.2.0
Using dm-migrations 1.2.0
Using do_sqlite3 0.10.17
Using dm-sqlite-adapter 1.2.0
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20190701
Using eventmachine 1.0.9.1
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using equalizer 0.0.11
Using erubis 2.7.0
Using espeak-ruby 1.0.4
Using execjs 2.7.0
Using geckodriver-helper 0.24.0
Using http-cookie 1.0.3
Using http-form_data 2.1.1
Using http 3.3.0
Using http-accept 1.7.0
Using json 2.3.0
Using maxmind-db 1.0.0
Using thread_safe 0.3.6
Using memoizable 0.4.2
Using mime-types-data 3.2019.1009
Using mime-types 3.3
Using mojo_magick 0.5.6
Using msgpack 1.3.1
Using msfrpc-client 1.1.2
Using multipart-post 2.1.1
Using mustermann 1.0.3
Using naught 1.1.0
Using netrc 0.11.0
Using parseconfig 1.0.8
Using power_assert 1.1.5
Using rqrcode_core 0.1.1
Using rqrcode 1.1.2
Using qr4r 0.4.1
Using rack-protection 2.0.7
Using rainbow 3.0.0
Using rdoc 6.2.0
Using rest-client 2.1.0
Using rexec 1.6.3
Using rr 1.2.1
Using rspec-support 3.9.0
Using rspec-core 3.9.0
Using rspec-expectations 3.9.0
Using rspec-mocks 3.9.0
Using rspec 3.9.0
Using rubydns 0.7.3
Using rubyzip 2.0.0
Using rushover 0.3.0
Using selenium-webdriver 3.142.6
Using simple_oauth 0.3.1
Using tilt 2.0.10
Using sinatra 2.0.7
Using slack-notifier 2.3.2
Using tins 1.22.2
Using term-ansicolor 1.7.1
Using test-unit 3.3.4
Using test-unit-context 0.5.1
Using test-unit-notify 1.0.4
Using test-unit-rr 1.0.5
Using test-unit-runner-tap 1.1.2
Using test-unit-full 0.0.5
Using thin 1.7.2
Using twitter 6.2.0
Using uglifier 4.2.0
Using xmlrpc 0.3.0

**Comment by Robin6464** [comment]
Maybe some gems are installed in wrong versions or too high ruby version. You should know it better and you can correct it.

**Comment by bcoles** [comment]
BeEF runs on Windows, but I wouldn't recommend it.

I also wouldn't recommend trying to support Windows. Support for Windows was dropped because the maintenance cost is too high.

**Comment by Robin6464** [comment]
Yes, it is known that beef is not supported under windows, but I think you mean running beef directly on windows using the installation of ruby under windows and copying files from devkit as given instructions for installing beef on windows from 2013. Nobody expects to include windows in the beef code. I tried unsuccessfully to run beef on windows without the help of cygwin. For various reasons, beef under a cygwin can only be an alternative :)

**Comment by bcoles** [comment]
> Nobody expects to include windows in the beef code and support

I suspect @jcrew99 may feel differently, which is why I commented, as a warning to prevent potential future pain.

On the other hand, a lot of functionality has been stripped out of BeEF recently (or is broken with no intention of fixing), which probably makes running BeEF on Windows easier.

However, I stand by my assertion that the maintenance cost of supporting Windows is too high, and pretending to support Windows only hurts users who will inevitably encounter issues only to discover there is no support.

Keeping up with webapp sec, browser sec, new browser versions released every 2 months, Ruby language updates, and Ruby dependency updates, all without introducing new bugs, on top of a decaying 10 year old code base, is a significant task in itself.

But it's not my call.

> Yes, it is known that beef is not supported under windows, but I think you mean running beef directly on windows using the installation of ruby under windows and copying files from devkit as given instructions for installing beef on windows from 2013 (only old beef versions works). [...] I tried unsuccessfully to run beef 0.4.7.4 on windows without the help of cygwin.

Running BeEF on Windows is not supported, even with the cygwin.

[The instructions you're referring to](https://github.com/beefproject/beef/issues/932#issuecomment-69188364), which also make use of cygwin, were related to setting up BeEF to push to Heroku. I chose to use Windows XP because I felt like a challenge at the time. I figured if I could get it working on the hellscape that is Ruby on Windows, then it should work everywhere. The instructions are referenced as installation instructions for Windows for no other reason than no other documentation exists, and it might be useful for someone insane enough to want to run BeEF on Windows.

It's great that you've written updated installation steps.

As an aside, in order to support Windows, there are [a non-trivial number of additional dependencies required to get the test suite running](https://github.com/beefproject/beef/blob/master/Gemfile#L64). If I recall correctly, I got most of the unit tests working, but never got the integration tests working.

> in gemfile set nokogiri 1.10.3 installed from cygwin repo

I believe the requirement for `gem 'nokogiri', '>= 1.10.4'` was for security reasons, although I'm not sure if BeEF was actually affected by the issues. Deliberately downgrading dependencies will introduce security flaws, introduce bugs, and increase maintenance overhead.

**Comment by Robin6464** [comment]
I understand you very well. My instructions on how to run beef in cygwin were to be used as a curiosity. I did not expect support. I can only write that I am very pleased to be able to fully use the new version of beef for windows in cygwin. This solved my problems with using beef on a virtual machine.

**Comment by jcrew99** [comment]
I wasnt really hoping to be able to support BeEF on windows, but i thought it was pretty cool that it could run on Windows, and that someone might find it useful if that was detailed somewhere with the disclaimer that there isn't any official support. 

I would ideally like to put in a wiki page something like the following:

"
Although Beef in Windows is not supported, a user has detailed the following instructions that seem to work.

Cygwin should have all the basic packages installed form cygwin repo, such as ssl, wget libraries etc. I will not mention all this and I assume that the basic packages are already installed in Cygwin.
I have installed ruby 2.6.4p104 in my cygwin form cygwin repo. I did not do "./install" and "bundle install" in beef folder because the default installation of byebug and nokogiri will fail. I installed byebug 11.0.1 and nokogiri 1.10.3 from the cygwin repository. In the cygwin I installed manually ("gem install ...") every gem from the gemfile file except nokogiri and byebug. In addition, I changed the version of nokogiri in gemfile from 1.10.4 to 1.10.3. Then I installed node-v12.13.1-x64 in windows and after installation it is recognized in cygwin. Finally, I changed the default password in the config.yaml file. That's all and now you should run beef.
"
@bcoles  do you think this may be detrimental at all?

**Comment by bcoles** [comment]
> 
> 
> I wasnt really hoping to be able to support BeEF on windows, but i thought it was pretty cool that it could run on Windows, and that someone might find it useful if that was detailed somewhere with the disclaimer that there isn't any official support.
> 
> I would ideally like to put in a wiki page something like the following:
> 
> "
> Although Beef in Windows is not supported, a user has detailed the following instructions that seem to work.

We used to do this, with the disclaimer `Windows is no longer supported. The following instructions are outdated.`.

https://github.com/beefproject/beef/wiki/Installation/_compare/716e0a9de1fc991061dd070c5e4728c401168a85...cca2da78371f6b7fdd124045b7dc0511a8fd5568

One user was upset and requested that the font size of the warning be increased. Not wanting to deal with it, I vaporized the instructions instead.

> @bcoles do you think this may be detrimental at all?

Unlikely, presuming sufficient warnings about lack of support and possible security issues with using outdated instructions and dependencies.

**Comment by jackdwalker** [comment]
@jcrew99 are you still planning on adding these instructions - making the disclaimer clear - to the Wiki or should this be closed off?

**Comment by jcrew99** [comment]
@jackdwalker  Thanks, missed this one and still planning on it.

**Comment by HYME60** [comment]
so.... are this is tools support to windows?

**Comment by DeezyE** [comment]
I don't believe there are plans to support windows. Closing this issue. Please reopen when necessary
