### ISSUE TITLE
Issue with dependencies.

### ISSUE THREAD

**Issue by SirEnvious** [beefproject/beef#1877]
I’m using the latest version of beef & ruby 2.5.3-3 

I’m trying to get BeEF to install on my iOS device but when I install it through my terminal it tells me I need to use brew.sh to install my dependencies and this is simply not possible, so I checked and found the dependencies required for it and managed to install every single dependency manually perfectly fine through cydia but when I try to install BeEF again it tells me I need to install the Brew.sh/ for the dependencies still.

If I could get some help with this because it would be amazing if I could get this to work, I already have SQLmap, Sherlock, Metasploit and some other tools installed and working.

**Comment by jcrew99** [comment]
@SirEnvious  Can you please provide more information about what you're using? 
Since you have installed via Cydia it sounds like you're using a jail broken IOS, would that be correct?
Beef isnt supported on those devices so it isnt a recommended way to try and get it working.

However you can go into https://github.com/beefproject/beef/blob/master/install and change up line 128 -152 to suit your installation. its likely that you will need to remove it and change the OS check as possible. Try making a pull request and playing around with it and try and get it to work. Look at line 45 - 47 for when its being called

**Comment by jcrew99** [comment]
@SirEnvious  Have you had any luck with the above, im curious? I will close this issue for now but re-open if you would like.
I have to re-iterate that beef isn't supported on what your device seems to be

**Comment by SirEnvious** [comment]
exciting news!! 

It’s almost working the only issue i’m having now is it requires brew to finish the installation but apart from that it should work fine since then I have got a ton of new tools to work also :)

**Comment by SirEnvious** [comment]
yes I know none of the tools I have working are supported for my device but they work! here’s a screenshot of all the tools I have: 


![845635F1-2927-4841-9F1E-E6EC8D005224](https://user-images.githubusercontent.com/61590409/79687091-b8e6bf00-823c-11ea-9c9e-be9b959f3afe.jpeg)
the most of these actually work
