### ISSUE TITLE
Can we get dns rebinding support to make performing such attacks possible and much easier ?

### ISSUE THREAD

**Issue by minanagehsalalma** [beefproject/beef#1913]
https://rhaidiz.net/2018/10/25/dribble-stealing-wifi-password-via-browsers-cache-poisoning/

https://sinister.ly/Thread-DNS-Rebinding-Attack

Both but especially the first one ... and what do you suggest would be a better name for it?

In the article he did it using i frame and a local http server to take advantage of cache poisoning which i couldn't fully understand.

Wouldn't a local dns server make it easier faster and more efficient ? Just like the second one but in local level + using karma attack.

What do you think ?

**Comment by jcrew99** [comment]
@minanagehsalalma Its a cool idea and definitely something worth looking at in the future.
I am not really familiar with it myself but worth putting some thought into and seeing if we can implement it at some point.
It sounds like a cool module to get going.

**Comment by bcoles** [comment]
> 
> 
> @minanagehsalalma Its a cool idea and definitely something worth looking at in the future.
> I am not really familiar with it myself but worth putting some thought into and seeing if we can implement it at some point.
> It sounds like a cool module to get going.

This should probably be implemented as an extension rather than a module; although the easy approach would be to leverage someone else's services, such as:

* https://lock.cmpxchg8b.com/rebinder.html

Also, there's already an [experimenal DNS rebinding extension](https://github.com/beefproject/beef/blob/master/extensions/dns_rebinding/config.yaml) in the framework.

There's a few frameworks available, such as:

* https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2018/august/singularity-of-origin-a-dns-rebinding-attack-framework/

Which offers a "temporary" service:

* http://rebind.it:8080/manager.html

**Comment by minanagehsalalma** [comment]
> Its a cool idea

@jcrew99 great you liked it..



> although the easy approach would be to leverage someone else's services,

@bcoles  Yup i agree with that ...... creating a one from scratch would take so long and would be missing some advanced features the framework you mentioned have...

**Comment by DeezyE** [comment]
Closing due to viable solutions available elsewhere. Reopen if necessary.
