### ISSUE TITLE
beef not working

### ISSUE THREAD

**Issue by user421921** [beefproject/beef#1943]
Verify first that your issue/request has not been posted previously:
#### Environment

What version/revision of BeEF are you using?
0.5.0.0
On what version of Ruby?
1:2.7+1
On what browser?
chrome, and Firefox
On what operating system?
windows 10 and parrot security OS with Firefox
windows 10 with chrome
#### Configuration

Are you using a non-default configuration?
no
Have you enabled or disabled any BeEF extensions?
no

#### Summary

Please provide a summary of the issue.
when i try to hook a browser it doesn't show up on my beef interface. i have an internet connection on all computers

#### Expected Behavior

What was the expected result?
it to show the hooked browser and let me do modules and extensions

#### Actual Behavior

What was the actual result?
no browsers shown to be hooked

#### Steps to Reproduce

Please provide steps to reproduce this issue.
i started beef on my parrot OS computer and i logged in to the web ui and i gave the second computer the both hook links and it was all on my LAN

#### Additional Information
these are the links i tried 
on my parrot machine:
127.0.0.1:3000/demos/basic.html
127.0.0.1:3000/demos/butcher/index.html

on my windows machine:
http://192.168.50.172:3000/demos/basic.html
http://192.168.50.172:3000/demos/butcher/index.html
[Aooo.txt](https://github.com/beefproject/beef/files/4795258/Aooo.txt)

**Comment by jackdwalker** [comment]
@user421921 we do not support/maintain BeEF for use on Windows, so we will be unable to assist you there sorry. I'll get back to you soon regarding your ParrotOS problems though - will attempt to reproduce.

**Comment by jackdwalker** [comment]
I am assuming since your problem is related to hooking browsers, and not loading BeEF you are using `beef-xss` as ParrotOS is having dependency problems that prevent the current release of BeEF from working.

I have not been able to replicate your problem, `beef-xss` appears to be working fine on ParrotOS from what I can see.

Could you please provide detailed steps to reproduce your problems and also capture the logs when you encounter this issue? To enable the debugging logs server-side please set `debug: true` in your `config.yaml` file, in `/usr/share/beef-xss`. Also provide the output of the service logs; these can be generated by running `journalctl -u beef-xss`. Finally if you could provide the client-side/console logs from both the attacking (ParrotOS) and victim (Windows 10) browsers (Ctrl + Shift + I).

**Comment by user421921** [comment]
Thank you so much for helping, luckily it’s working now, if I have any more
problems I’ll tell you, thank you for everything
