### ISSUE TITLE
Framework is down

### ISSUE THREAD

**Issue by ms3c** [beefproject/beef#1945]
Verify first that your issue/request has not been posted previously:

* https://github.com/beefproject/beef/issues
* https://github.com/beefproject/beef/wiki/FAQ

Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.5.0.0).

#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?

#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?

#### Summary

Please provide a summary of the issue.

#### Expected Behaviour

What was the expected result?

#### Actual Behaviour

What was the actual result?

#### Steps to Reproduce

Please provide steps to reproduce this issue.

#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots. Debug output can be enabled by specifying `debug: true` in the `config.yaml` configuration file.

**Comment by ms3c** [comment]
i got this error beef is telling me framework is down, I think I have too many victims or ?

**Comment by JBalanza** [comment]
What error? you didn't fill the issue template

**Comment by jcrew99** [comment]
@ms3c  Can you please fill out the error template?

**Comment by bcoles** [comment]
`The framework is down` is an error returned in the web interface. This happens when the user's web browser attempts to poll the BeEF admin UI but the connection times out. The most common cause is killing the BeEF process while leaving the web browser open. Then, obviously, the browser will not be able to communicate with the server.

However, in this instance, OP is suggesting that perhaps they have too many hooked browsers which is causing the poll from the browser to the admin UI to time out. This might be possible, especially with a large number of hooked browsers polling the server on a short polling interval (ie, 1 second).

**Comment by jackdwalker** [comment]
Closing due to lack of response. If you continue to have similar issues @ms3c please re-open this with steps to reproduce (including information requested in our issue template) or feel free to raise a new issue.

**Comment by moleisking** [comment]
In my case it was a nginx rewrite rule that was creating excessive polling via the browser at the url root path.
