### ISSUE TITLE
not injecting mitm hook js

### ISSUE THREAD

**Issue by QairexStudio** [beefproject/beef#1980]
hey bro. mitmf is injecting the hook.js but cannot showing in the offline/online webbrowser ?

**Comment by bcoles** [comment]
If you want assistance with your question it would be beneficial to provide substantially more evidence.

What did you find when you were debugging the issue?

**Comment by QairexStudio** [comment]
> If you want assistance with your question it would be beneficial to provide substantially more evidence.
> 
> What did you find when you were debugging the issue?

nothing. as i told. ok wait along: look picture:

**Comment by jcrew99** [comment]
Hi @QairexStudio,

You haven't really described your issue well enough for us to assist.
when you create an issue it uses a template which can be found below.
(found here - https://github.com/beefproject/beef/blob/master/.github/ISSUE_TEMPLATE.md)

Please comment with those actions taken and questions filled out.
We cannot help you unless we get that information, feel free to let us know if you are having any trouble or issues with doing so.  

Otherwise we would close this ticket due to lack of information.

cheers

**Comment by jcrew99** [comment]
closing due to needing update
