### ISSUE TITLE
./install: line 176: RUBY_VERSION: command not found [INFO]  Updating rubygems... sudo: gem: command not found

### ISSUE THREAD

**Issue by tanjhysj0** [beefproject/beef#1996]
```
$ ./install 

gcc-9-base is already the newest version (9-20190428-1ubuntu1~18.04.york0).
libgcc-9-dev is already the newest version (9-20190428-1ubuntu1~18.04.york0).
The following package was automatically installed and is no longer required:
  linux-modules-4.15.0-29-generic
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
[INFO]  Ruby package Manager exists - Ruby install skipped
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.7.0 is installed
./install: line 176: RUBY_VERSION: command not found
[INFO]  Updating rubygems...
sudo: gem: command not found
ubuntu@VM-0-13-ubuntu:~/beef$ gem -v
3.1.2

```
if I install ruby 2.5 ,It's show :error:ruby not install

**Comment by tanjhysj0** [comment]
[INFO]  Ruby package Manager exists - Ruby install skipped
[INFO]  Detecting Ruby environment...
[INFO]  Ruby version 2.5.3@beef is installed
./install: line 176: RUBY_VERSION: command not found
[INFO]  Updating rubygems...
sudo: gem: command not found

**Comment by jcrew99** [comment]
@tanjhysj0  Interesting, my experience with
`` sudo: gem: command not found``
Is that it relates to your ruby environment.
Needless to say there has always been a big conversation about managing the ruby environment but where it currently stands may not be working for you with how your environment is configured.
I believe it will be doing 
``sudo gem -v``
where your install of ruby isn't root, which is why you can do.
``gem -v``
I believe our install script was modified to handle this so this should have a workable fix.
I'll test it out later and make a merge request if so otherwise will update.

**Comment by th3sp1s** [comment]
I am experiencing the same problem after cloning the repository on nov 19th.

Additionally, as a different issue, I had to run `source ~/.rvm/scripts/rvm` before `rvm install "ruby-2.5.3"` .
And also I had to manually install gcc-9.

**Comment by th3sp1s** [comment]
None of the mentioned issues (except gcc-9) show up by installing ruby with regular `sudo apt install ruby` on a fresh Ubuntu 18.04.

Also runing `./install` with sudo will avoid **_There was an error while trying to write to `/opt/beef/.bundle/config`._**

**Comment by DeezyE** [comment]
This sounds like the prerequisites (ruby etc) listed here: https://github.com/beefproject/beef/wiki/Installation were not installed
