### ISSUE TITLE
YT video question

### ISSUE THREAD

**Issue by buds8489** [beefproject/beef#2072]
Hi, i found this video tutorial showing exactly what i want to do, but it was made 4 years ago and im sure nobody is going to awnser my comment, My question is, do i need my victims ip adress to do this?    https://www.youtube.com/watch?v=VP_9CHteEBU   , if you dont feel safe clicking the link, the video is called "MITMF + BEEF + DRIFTNET + METASPLOIT - Kali Linux" and its by Cosmic 2x4

**Comment by bcoles** [comment]
> My question is, do i need my victims ip adress to do this?

In the video they are using `mitmf` to target a specific host on the network (rather than middling the entire network). This is probably for convenience and demonstration purposes. You can middle an entire network, but be aware that your network adapter may not have sufficient throughput to handle all the traffic. If you're using virtual machines in a lab you also risk middling the hypervisor host which won't end well.

**Comment by wheatley** [comment]
> Hi, i found this video tutorial showing exactly what i want to do, but it was made 4 years ago and im sure nobody is going to awnser my comment, My question is, do i need my victims ip adress to do this? https://www.youtube.com/watch?v=VP_9CHteEBU , if you dont feel safe clicking the link, the video is called "MITMF + BEEF + DRIFTNET + METASPLOIT - Kali Linux" and its by Cosmic 2x4

***warning*** mute when playing that video.
