### ISSUE TITLE
Add BrowserStack testing to PR

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2158]
Currently BrowserStack testing is not being triggered when a PR is created.
In order to help developers know if what their changing as broken anything we should set up some basic tests to give some guidance.

**Comment by jackwalker-ripmfa** [comment]
@wheatley - BrowserStack testing was removed due to the amount of PRs it was breaking. My initial implementation was becoming a blocker and impeding active development from memory. One could argue that it was serving its purpose, but due to the fact it was still somewhat buggy there was an growing distrust in its results.

My personal opinion on the matter is that BeEF shouldn't need to support some of the really, really legacy browsers that were originally discussed as being 'in-scope' for development considerations. The degree to which it slowed production down did more harm to the project than it did good. 

If it is re-integrated into PRs, I would strongly consider evaluating a more healthy balance of browsers. For example, I'd suggested discarding anything before Firefox 30/Chrome 35/Safari 6.2 (can keep legacy IE). I'm no expert, so my opinion probably doesn't count for much but I highly doubt these have any modicum of use anymore, or at least a small enough percentage that development progress (on a project that needs support as is) should be inhibited as a result of their consideration.

Just my 2c.

**Comment by bcoles** [comment]
> For example, I'd suggested discarding anything before Firefox 30/Chrome 35/Safari 6.2 (can keep legacy IE).

If your goal is to make maintenance easier then IE should be the first to go.

**Comment by jackwalker-ripmfa** [comment]
> 
> 
> If your goal is to make maintenance easier then IE should be the first to go.

Fair point. I feel like legacy IE is far more likely to exist in the wild than Chrome 20. As mentioned at the end of the section you quoted:

> For example, I'd suggested discarding anything before Firefox 30/Chrome 35/Safari 6.2 (can keep legacy IE) **at an absolute minimum**.

I'm all for IE going.

**Comment by bcoles** [comment]
This is done.

**Comment by Andy340** [comment]
How to merge PR for browser stack. Please guide me i need help
