### ISSUE TITLE
Install Script: Remove --without test develop from ./install

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2179]
https://github.com/beefproject/beef/blob/1ae320c3bc9db748dff7e53fe919cdef80089062/install#L240

is deprecated and should be removed
bundle not requires a local config file to store this information

**Comment by mateuseap** [comment]
It's an old issue, but I'd like to know if I can still work on this :)

**Comment by wheatley** [comment]
Go for it, reach out if you need any help.

**Comment by bcoles** [comment]
@mateuseap I'm not entirely sure what the original issue is or if it still exists, but sure. The installer could do with more review / testing anyway.

This related code segment looks like it might contain a bug. The first conditional branch checks for `bundler<version>` instead of `bundle<version>`. I don't think that's correct. If I recall, this was added for BSB (FreeBSD) systems which installed bundler with the version suffix by default. It's possible that it uses `bundler` for some reason.

```bash
  if command_exists bundler${RUBYSUFFIX}
  then
    bundle${RUBYSUFFIX} install --without test development
  else
    bundle install --without test development
  fi
```
