### ISSUE TITLE
Installing beef via apt

### ISSUE THREAD

**Issue by Binula-Kavisinghe** [beefproject/beef#2221]
Is it possible to install beef by the command,

> **sudo apt install beef-xss**

as shown in the [kali documentation?](https://www.kali.org/tools/beef-xss/)

Are there any tradeoffs like fewer features, less frequent updates, etc...  as opposed to cloning the git repository?

**Comment by bcoles** [comment]
> 
> 
> Is it possible to install beef by the command,
> 
> > **sudo apt install beef-xss**
> 
> as shown in the [kali documentation?](https://www.kali.org/tools/beef-xss/)

Yes it is possible to install the BeEF package using the system package manager (`apt` on Debian based systems, including Kali) on systems which have a BeEF package (Kali, Parrot, BackBox?).

> Are there any tradeoffs like fewer features, less frequent updates, etc... as opposed to cloning the git repository?

Packages require package maintainers to pull the latest official release, configure the software appropriately, and perform any necessary testing, then create and distribute the package.

On Kali, for a long time, the `beef-xss` package was extremely out of date, mostly due to BeEF development efforts occurring in the git repo without producing a new official release. I believe this situation has been resolved recently.

In theory, using the `beef-xss` package for your operating system should be configured and tested to work correctly for your operating system.

Using BeEF from the git repository will give you the latest features and bug fixes. However, the git repo is under continuous development and may contain bugs.

**Comment by wheatley** [comment]
to quote @DeezyE 

> @Binula-Kavisinghe Thanks for the contribution to Beef, I'm glad that you've taken the time to work on it. As this addresses an issue with beef-xss and breaks this beef repo we won't merge it.
However there's some work that we're planning to do with aligning the Kali package and this one (ideally removing the differences between)
Would you be keen on working on that (or another feature) with us?

and 

> @Binula-Kavisinghe just email discord@bindshell.net if you'd like to join the contributors discord

**Comment by wheatley** [comment]
Closing as this has gone stale.
