### ISSUE TITLE
extensions/admin_ui/handlers/ui.rb: todo: Determine why this class is calling super?

### ISSUE THREAD

**Issue by bcoles** [beefproject/beef#2288]
434779055ca3682cb3256a4366ccadd7b83de7b2 apparently fixed a bug.

In doing so, `super` was commented out, and a mysterious comment left in its place.

https://github.com/beefproject/beef/blob/ae9976b0501e7efe4f71e231bb7679b35537cc97/extensions/admin_ui/handlers/ui.rb#L18-L22

**Comment by jcrew99** [comment]
I can't quite say why antisnatchor included used it when he added it 11 years ago, but by reading through the commit, i think at that time there was an inherited initialize class that they wanted to run that touched on authentication in the admin_ui. Since it's changed a lot since then, it's hard to say.

So when i uncommented the super line it stopped me from being able to authenticate at all. So having it in place is breaking that extension.

After reading the bugfix name and considering the error that popped referred to the API::Handler providing too many arguments, i changed it to super() so that it would provide none and to see what it did.

It fixed the api_fire error and resolved the authentication issues that the admin_ui was having but it doesn't actually show what the difference between having it commented out or not does.

So i stepped through both of them with byebug and apparently it doesn't really matter, they error either way!

Here it is with super() uncommented:

`                                                                                                                     [14, 23] in beef/extensions/admin_ui/handlers/ui.rb                                                         
14:                                                                                                                 
15:           # Constructor                                                                                          
16:           #                                                                                                      
17:           def initialize(klass)                                                                                  
18:              # @todo Determine why this class is calling super?                                               => 
19:              require byebug ; byebug                                                                             20:              super()                                                                                             
21:             @klass = BeEF::Extension::AdminUI::Controllers.const_get(klass.to_s.capitalize)                      22:           end                                                                                                    
23:                                                                                                               (byebug) s                                                                                                                                                                                                                                [196, 205] inbeef/core/api.rb                                                                              196:           # print_info "API: #{mod} fired #{method}"                                                            197:                                                                                                                 198:           result = mod[:owner].method(method).call(*args)                                                       199:           data << { api_id: mod[:id], data: result } unless result.nil?                                         200:         rescue StandardError => e                                                                            => 201:           print_error "API Fire Error: #{e.message} in #{mod}.#{method}()"                                      202:         end                                                                                                     203:                                                                                                                 204:         data                                                                                                    205:       end                                                                                                    (byebug) e.message                                                                                                   "no implicit conversion of nil into String"                                                                          (byebug) mod                                                                                                         {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>22}                                                            (byebug) #{mod}.#{method}()                                                                                          nil                                                                                                                  (byebug)      
`

Here it is with super commented out:

`
[14, 23] in beef/extensions/admin_ui/handlers/ui.rb
   14:           #
   15:           # Constructor
   16:           #
   17:           def initialize(klass)
   18:              # @todo Determine why this class is calling super?
=> 19:              require byebug ; byebug
   20:              #super
   21:             @klass = BeEF::Extension::AdminUI::Controllers.const_get(klass.to_s.capitalize)
   22:           end
   23:
(byebug) s
[196, 205] in beef/core/api.rb
   196:           # print_info "API: #{mod} fired #{method}"
   197:
   198:           result = mod[:owner].method(method).call(*args)
   199:           data << { api_id: mod[:id], data: result } unless result.nil?
   200:         rescue StandardError => e
=> 201:           print_error "API Fire Error: #{e.message} in #{mod}.#{method}()"
   202:         end
   203:
   204:         data
   205:       end
(byebug)  #{e.message}
nil
(byebug) #{mod}.#{method}()
nil
(byebug) mod
{:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>22}
(byebug) method
:mount_handler
(byebug) #{method}()
nil
(byebug)
`

So i tried it with the original `super` uncommented, which has the same output as the above `super()` , except it actually prints the error. 

So far i have to believe it's some form of race condition, as when i byebug the error it will print it, but when i don't it will jump over it, which is perhaps something that  using `super` is allowing for.

Either way, it appears an error is occurring regardless, with no `super` or using `super()`, it's just that using `super`  is actually just breaking the authentication functionality. 

It get's pushed into the rescue standard error regardless, but so far, nothing actually appears broken if it's commented out or it is `super()`. Although that's in part because i can't tell what exactly it's intending for it to do as it appears to achieve what its trying to do :/ 

`
[196, 205] in beef/core/api.rb
   196:           # print_info "API: #{mod} fired #{method}"
   197:
   198:           result = mod[:owner].method(method).call(*args)
   199:           data << { api_id: mod[:id], data: result } unless result.nil?
   200:         rescue StandardError => e
=> 201:           print_error "API Fire Error: #{e.message} in #{mod}.#{method}()"
   202:         end
   203:
   204:         data
   205:       end
`

I honestly just recommend that we either remove the two comments or just change it to be `super()` and uncomment it.

Let me know what you think and i can make a pull request if you agree with it being appropriate at all.

**Comment by bcoles** [comment]
> So far i have to believe it's some form of race condition, as when i byebug the error it will print it, but when i don't it will jump over it, which is perhaps something that using `super` is allowing for.

It may be more sinister than a race condition. Reminds me of this bug which can only be triggered when debugging is enabled. #1856

> So i tried it with the original `super` uncommented, which has the same output as the above `super()` , except it actually prints the error.

That seems unlikely. `super` and `super()` are the same thing... unless we've somehow monkey patched `super` somewhere (please no).

> I honestly just recommend that we either remove the two comments or just change it to be `super()` and uncomment it.

Those are the two options, yes. Pick one and roll with it.

> Let me know what you think and i can make a pull request if you agree with it being appropriate at all.

If it doesn't need to call `super` then I'd just remove it.

**Comment by jcrew99** [comment]
Hmm that's a good point, maybe there's more to be done there. Probably should give @jcrew99  a kick in the pants on it.

Just a note on super, they're differ as they determine the arguments that get sent:
super - sends all arguments
super() - no arguments
I don't really wanna deal with super being monkey patched so im just gonna cross my fingers on that one.

This is why the original bugfix that comment is from happened because this error was showing up on the console:
`
 API Fire Error: wrong number of arguments (given 1, expected 0) in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>22}.mount_handler()
 `
 The reason this shows is because it's a different error then what would "appear" to  to be going wrong. I believe its trying to pass the klass argument.
  
 `
 [15, 24] in beef/extensions/admin_ui/handlers/ui.rb
   15:           #
   16:           # Constructor
   17:           #
   18:           def initialize(klass)
   19:             # @todo Determine why this class is calling super?
=> 20:             require byebug ; byebug
   21:             super
   22:             @klass = BeEF::Extension::AdminUI::Controllers.const_get(klass.to_s.capitalize)
   23:           end
   24:
 (byebug) super()
nil
(byebug) super
*** ArgumentError Exception: wrong number of arguments (given 1, expected 0)

nil
(byebug)
`
Regardless, i agree, it's best just to remove it.
I'll @ you in the pull request.

**Comment by bcoles** [comment]
> Just a note on super, they're differ as they determine the arguments that get sent: super - sends all arguments super() - no arguments I don't really wanna deal with super being monkey patched so im just gonna cross my fingers on that one.

welp TIL. The original code used `super()` before it was commented out.

> Regardless, i agree, it's best just to remove it. I'll @ you in the pull request.

Don't bother. Just make sure the tests run and merge it.

**Comment by jcrew99** [comment]
Ahh that would make sense, thanks for that!
