### ISSUE TITLE
dynamicreconstruction error with ruby 3.1.1

### ISSUE THREAD

**Issue by wheatley** [beefproject/beef#2324]
Not sure why this error is happening, but when I was hooking Brave browser going to Beef Basic it was throwing this error.

Docker - ubuntu:20.4
Ruby - 3.1.1
Hooked browser - [Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)](https://brave.com/latest/)

This issue is for reference:

`#<Thread:0x00007f851464c418 /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:45 run> terminated with exception (report_on_exception is true):
/root/beef/extensions/events/handler.rb:48:in `[]': no implicit conversion of String into Integer (TypeError)
        from /root/beef/extensions/events/handler.rb:48:in `parse'
        from /root/beef/extensions/events/handler.rb:43:in `block in setup'
        from /root/beef/extensions/events/handler.rb:42:in `each'
        from /root/beef/extensions/events/handler.rb:42:in `setup'
        from /root/beef/extensions/events/handler.rb:17:in `initialize'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:100:in `new'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:100:in `execute'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:74:in `block in check_packets'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:53:in `each'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:53:in `check_packets'
        from /root/beef/core/main/network_stack/handlers/dynamicreconstruction.rb:46:in `block (2 levels) in <class:DynamicReconstruction>'`

**Comment by DeezyE** [comment]
Must be the docker, Brave hooks fine regularly.

**Comment by bcoles** [comment]
The backtrace refers to these lines:

https://github.com/beefproject/beef/blob/bcd08657f1156b7790b352f7edccde0bc862a476/extensions/events/handler.rb#L40-L45

Typically, `events` contains an `Array` of `Hash`. Each event `hash` is passed to `parse`.

https://github.com/beefproject/beef/blob/bcd08657f1156b7790b352f7edccde0bc862a476/extensions/events/handler.rb#L47-L48

Presumably, one of the `events` is not a `Hash`... for some reason... causing Ruby to treat `'type'` in `event['type']` on line 48 as an Array index instead of a Hash key.

I was able to trigger the issue by forcing an Array into the events Array: `events.append(['asdf'])`

I have not been able to reproduce this issue in practice, but it has been reported by at least one other user.
