### ISSUE TITLE
cant login into beef

### ISSUE THREAD

**Issue by Lukasso33** [beefproject/beef#2406]
after entering the correct password and login in the beef console, the page loads but redirects me back to the beef login screen

**Comment by bcoles** [comment]
The login page uses a CSRF token, which will be invalid if you restart the server. You may need to reload the login page or simply try logging in again.

**Comment by xavitc100** [comment]
Hi, i can't login to the page after typing the credentials, the page loads and redirects me to the login screen again. I use ngrok
<img width="588" alt="Captura de pantalla 2022-05-14 231821" src="https://user-images.githubusercontent.com/105455831/168448459-1179a9b8-933c-4e9c-b766-98ab935c268a.png">
I put the ngrok id like it's in the wiki but i can't access. 
This is how i do it
1 - I start ngrok to see the id
2 - I copy the id in the config.yaml
3 - I start beef

I use Beef-Over-The-Wan to use beef outside my local network but i don't know if just with ngrok i can do it or i really need to use Beef-Over-The-Wan, i'm getting confused on that point. If someone can explain me that point it will be amazing. I'm trying to login with the URLs that Beef-Over-The-Wan provides me and the URLs that beef provides and with the IPs of the networks interfaces i can login.
<img width="1843" alt="Captura de pantalla 2022-05-14 233815" src="https://user-images.githubusercontent.com/105455831/168448888-a4b18111-2b05-4a20-9030-25529cf29b30.png">
In this screenshot i think you can see all the process i do. Pls if someone could explain me a bit or help me i will be very greatful. I want to learn this kind of stuff because i think is super interesting but sometimes is a bit confusing for me especially when I've been trying a lot of things for hours

**Comment by wheatley** [comment]
hey @xavitc100 if you are attempting to use ngrok please check this guide [here](https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok). 

If you are still requiring to use beef-over-the-wan please log a support [ticket](https://github.com/stormshadow07/BeeF-Over-Wan)
