### ISSUE TITLE
Google Browser

### ISSUE THREAD

**Issue by Lucidyyyy** [beefproject/beef#2444]
If i am using beef panel that works, how can i send the link to hack someone from the kali linux system and so it works on google, because when i open the hacked link on google it says it cant be reached

**Comment by kyleparker134** [comment]
im having this problem too

**Comment by wheatley** [comment]
hey @Lucidyyyy and @kyleparker134 could you please provide us with the following information so we can help you.

## Environment

*Please identify the environment in which your issue occurred.*

1. **BeEF Version:**

2. **Ruby Version:**

3. **Browser Details (e.g. Chrome v81.0):**

4. **Operating System (e.g. OSX Catalina):**


## Configuration

**Q:** Have you made any changes to your BeEF configuration? 
**A:**

**Q:** Have you enabled or disabled any BeEF extensions?
**A:**

## Expected vs. Actual Behaviour

**Expected Behaviour:** 
<br />
**Actual Behaviour:**
<br />

## Steps to Reproduce

*Please provide steps to reproduce this issue.*

1.

**Comment by hetsaraiya** [comment]
Ruby version: 3.0.3p157
Chrome version: 102.0.5005.63
Operating system: kali linux (victim: windows 11)

Have you made any changes to your BeEF configuration?
A: no

Have you enabled or disabled any BeEF extensions?
A: no

Expected Behaviour: victim browser could be able to access link given to him/her


Actual Behaviour: victim's browser is not letting him/her access that link on chrome
<img width="508" alt="Screenshot 2022-06-11 115919" src="https://user-images.githubusercontent.com/83812167/173176258-5a436971-f280-40ed-a64f-e64b3afd951b.png">

**Comment by bcoles** [comment]
> Actual Behaviour: victim's browser is not letting him/her access that link on chrome <img alt="Screenshot 2022-06-11 115919" width="508" src="https://user-images.githubusercontent.com/83812167/173176258-5a436971-f280-40ed-a64f-e64b3afd951b.png">

`127.0.0.1` is the local loopback network interface. It is not reachable from other hosts. Use a hook URL for an IP address associated with a LAN interface.

If the browser to be hooked is running on a host which is not on the local network, you will need to port forward or tunnel traffic to the BeEF host. Refer to:

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
