### ISSUE TITLE
BeEF geoip issue

### ISSUE THREAD

**Issue by itzausername** [beefproject/beef#2452]
Hi, i'm having issues with beEF.
As you can see my beEF server won't start up.

I'm using unbuntu and i am on Windows. I followed this tutorial https://youtu.be/hD_JRo7YPcg

I didn't add any extension or used any scripts.

What i am trying to achieve here is trying to enter my ui url for some reason it won't allow me to connect

https://user-images.githubusercontent.com/107043608/172371059-9e587527-95b8-47c8-b5f9-a1d63450168d.png

https://user-images.githubusercontent.com/107043608/172371219-4f114839-aacf-40b3-9601-380d72b7c16e.png

**Comment by bcoles** [comment]
> Hi, i'm having issues with beEF. As you can see my beEF server won't start up.

The screenshot shows that the BeEF server started.

> I followed this tutorial https://youtu.be/hD_JRo7YPcg
> https://user-images.githubusercontent.com/107043608/172371059-9e587527-95b8-47c8-b5f9-a1d63450168d.png

That unofficial video is a few years old. MaxMind have since changed how the database is distributed.

https://github.com/beefproject/beef/wiki/Geolocation#create-maxmind-account-and-download-mmdb

> https://user-images.githubusercontent.com/107043608/172371219-4f114839-aacf-40b3-9601-380d72b7c16e.png

It is unclear what you're trying to achieve here. The only relevant part of the screenshot is redacted.

**Comment by itzausername** [comment]
the beef server won't start up

**Comment by bcoles** [comment]
> the beef server won't start up

Where did you get stuck during troubleshooting?

**Comment by itzausername** [comment]
i didn't. i followed the tutorial

**Comment by bcoles** [comment]
There is not enough information to offer guidance. Attempt troubleshooting and post where you get stuck.
