### ISSUE TITLE
how to put the <script hook.js> in a https web?

### ISSUE THREAD

**Issue by BlackDemonHat** [beefproject/beef#2540]
if i create a web with a ssl certificate the hook.js wont work and worn work with https beef

**Comment by bcoles** [comment]
> if i create a web with a ssl certificate the hook.js wont work

Browsers won't load JavaScript hosted on HTTP from HTTPS. You will need to run BeEF with HTTPS or use a front end reverse proxy which uses HTTPS, like ngrok.

> and worn work with https beef

Presumably it won't work because you're using an untrusted ceritifcate.

**Comment by bcoles** [comment]
> @bcoles yes i tried with beef https but did't work

Presumably it won't work because you're using an untrusted certificate.

Browsers won't load JavaScript hosted on HTTP from HTTPS. You will need to run BeEF with HTTPS or use a front end reverse proxy which uses HTTPS, like ngrok.

You will not be able to hook browsers on HTTPS websites unless you can load the hook from a HTTPS URL with a trusted certificate.
