### ISSUE TITLE
Beef over wan with page kite

### ISSUE THREAD

**Issue by ChillVibesMushroom** [beefproject/beef#2669]
Can I use page kite with beef or does it explicitly have to be ngrok

**Comment by bcoles** [comment]
I have no idea what page kite is, but if it allow you to tunnel HTTP(S) traffic, then yes.

The only reason you need ngrok (or any other tunneling software) is if you're running BeEF in a NAT'd environment (or a host in an environment that is otherwise segmented from the public Internet by firewall rules).

You want browsers to connect back to your server. For this, you need will need to change the `public` properties in the configuration file.

* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
* https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok

If your ISP does not implement CG-NAT and you are comfortable with configuring port forwarding on your router then you don't need any tunneling software at all. Simply forward ports from the border router to your host running BeEF. Of course, services like ngrok offer valid trusted TLS certificates which makes setup easier, as self-signed certificates won't be trusted by other user's browsers.

**Comment by ChillVibesMushroom** [comment]
> I have no idea what page kite is, but if it allow you to tunnel HTTP(S) traffic, then yes.
> 
> The only reason you need ngrok (or any other tunneling software) is if you're running BeEF in a NAT'd environment (or a host in an environment that is otherwise segmented from the public Internet by firewall rules).
> 
> You want browsers to connect back to your server. For this, you need will need to change the `public` properties in the configuration file.
> 
> * https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-on-a-server-behind-nat
> * https://github.com/beefproject/beef/wiki/FAQ#how-do-i-configure-beef-with-ngrok
> 
> If your ISP does not implement CG-NAT and you are comfortable with configuring port forwarding on your router then you don't need any tunneling software at all. Simply forward ports from the border router to your host running BeEF. Of course, services like ngrok offer valid trusted TLS certificates which makes setup easier, as self-signed certificates won't be trusted by other user's browsers.

So I just run my page on port 80 with the beef script 

Tunnel using port 80 with page kite 

page kite  https://pagekite.net/ and visit the panel on my local ipv4?

**Comment by bcoles** [comment]
BeEF runs on port 3000 by default. You'll want to tunnel port 80 to 3000 if Page Kite supports it. otherwise you'll need to run BeEF on port 80.

**Comment by ChillVibesMushroom** [comment]
> BeEF runs on port 3000 by default. You'll want to tunnel port 80 to 3000 if Page Kite supports it. otherwise you'll need to run BeEF on port 80.

So then I need two tunnels I need one for 3000 and on for my web page on 80

both http
