### ISSUE TITLE
undefined method `exists?' for File:Class (NoMethodError) Did you mean?  exist?

### ISSUE THREAD

**Issue by as9697347** [beefproject/beef#2739]
undefined method `exists?' for File:Class (NoMethodError)
Did you mean?  exist?
ruby version: ruby 3.2.1 (2023-02-08 revision 31819e82c8)

**Comment by bcoles** [comment]
Thanks. `File.exists?` was deprecated in Ruby 2.1.0 and has been removed in the Ruby 3.2.0.

* https://bugs.ruby-lang.org/issues/17391
* https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/

This should be fixed in #2740 which has been merged into `master` branch.
