### ISSUE TITLE
Add tag-value hooked browser attributes to the database

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#581]
Alter the module API to permit results from modules to set generic tag-value settings in the database. These values can be retrieved and employed by other modules. For example, one module might determine the internal ip address of the hooked browser. This would then be stored in the database. This tag-value pair could be used but another module for an input setting.

**Comment by bcoles** [comment]
Elaborating on the above OP.

This is kind of being done now, albeit poorly, through the `BrowserDetails` model and the Autorun Rules Engine (ARE).

All command results are stored in the database, however searching through the command results is not ideal.

The `BrowserDetails` model is populated upon hook init, and later populated/updated via various extensions and command modules (some modules use the `post_execute` method to interact with models/extensions).

Replacing (renaming?) the `BrowserDetails` model in favor using it as a generic key=>data store is a viable option.

The entire hook initialisation and `BrowserDetails` workflow needs a rework, and should be reviewed as part of #1392. This functionality was written a long time ago, and doesn't play nicely with other functionality, such as WebSockets and the Autorun Rules Engine (ARE).

Traditionally, command modules have stored data, which may then be leveraged by extensions (rather than other modules). In instances where extensive use of the results was required elsewhere in the framework, a solution was lazily hacked together using unmaintainable code that generally ignored existing APIs.

The ARE was an attempt to remedy this. However, the ARE is overly complex for simple tasks, yet not sufficiently robust to complete complex tasks. The results from modules are either executed sequentially or passed along to other modules in a flimsy chain (`nested-forward`). While this is an improvement, it's more of a stop gap measure. It simply moves the problem somewhere else.

Currently, an ARE rule chain cannot fork mid-chain by passing the results onto more than one module; and results from one chain cannot be passed to another ARE chain. The argument could be made that such complex chains should be moved into their own extension; but this only moves the problem again.

What we've ended up with is another DSL on top of the existing API, where even the most contrived use cases require multiple lines of spaghetti (JavaScript buried in JSON), and anything beyond simple use cases requires masses of code duplication. An undesirable side-effect is running the same command modules multiple times, simply to retrieve information we already have.

This model ultimately results in the requirement for features such as [manually triggering an ARE rule](https://github.com/beefproject/beef/wiki/Autorun-Rule-Engine#trigger-rule) which is irrelevant to autorun, and would be more suited to a scripting engine; and results in feature requests such as #1153. What the author really wants is to be able to invoke a scripted set of actions on one or more hooked zombie(s). Autorun is inconsequential. Furthermore, this approach results in feature requests such as #1353, which *is* related to autorun, and highlights the shortcomings of this approach.

The RESTful API can be used to perform some scripting activities, however this is not a substitute for a scripting engine, as the processing is not performed locally, and must rely on polling the BeEF server. This is slow and adds extra overhead to the BeEF server, which is already getting hammered by zombies calling home.

**The only viable solution to the entire mess is the implementation of an event-driven model in combination with a scripting engine. The ARE got us part way there; however, a lot of reworking is required.**

The implementation of an event-driven model is no easy task, and will require storing a large amount of state information in the database, as scripts must know whether they can ignore an event. ie, has this script already run on this zombie?

Scripts and extensions should be permitted to register (and de-register) hooks to various areas of the API, such as new zombie connecting and receiving data from a zombie.

Existing ARE rules should be converted to scripts.

REST clients could also subscribe to events for remote processing, rather than polling.
