### ISSUE TITLE
Move to Ruby 2.x

### ISSUE THREAD

**Issue by wadealcorn** [beefproject/beef#997]
Drop support for ruby <2.0 and move to ruby 2.x

Ruby security maintenance timelines:  
https://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering

**Comment by xntrik** [comment]
@wadealcorn unsure. But, I think we should shift to supporting/supplying .ruby-version and .ruby-gemset files (and potentially stop excluding the Gemfile.lock file). Both of these things would help standardise on our development environments (and both these things are currently what the MSF guys do too)

**Comment by wadealcorn** [comment]
Makes sense. Is anyone keen to list this off?

**Comment by xntrik** [comment]
Is this still an issue? I've been running on 2.2.1 without issues. I believe @bcoles has also run numerous tests on Kali with different 2.2.* ruby versions too.

**Comment by bcoles** [comment]
Unit and Integration tests are passing with:

* Ruby 1.9.3-p551 on Kali with RVM
* Ruby 2.1.5-p273 on Kali
* Ruby 2.1.5 on Debian 8.1 with RVM
* Ruby 2.1.5 on Fedora 19 with RVM
* Ruby 2.1.6 on Fedora 19 with RVM
* Ruby 2.1.6 on Kali
* Ruby 2.1.6 on Kali with RVM
* Ruby 2.2.2 on Fedora 19 with RVM
* Ruby 2.2.2 on Kali with RVM


Metasploit integration tests are failing.

The integration tests for the DNS extension and WebRTC extension are failing. They aren't part of the default test suites.

@byt3bl33d3r has contributed `.ruby-version` and `.ruby-gemset` files here:
https://github.com/beefproject/beef/pull/1132

I've contributed a Gemfile.lock 96dcba967b17629cfc76548f210c8297f3552428 which may need changes.

**Comment by bcoles** [comment]
BeEF now requires Ruby 2.0+ for at least one dependency - see #1107.

BeEF has been updated accordingly:

* BeEF now exits is `RUBY_VERSION < 2.0`
* Some Ruby 1.9 compatibility code has been removed (for encoding, which is "fixed" since Ruby 2.0).
* Documentation and install scripts have been updated for Ruby 2.1.5, although only partially tested (OSX, anyone?).
* `.ruby-version` specifies the latest and greatest version of Ruby in the 2.x branch (version 2.2.4 at time of writing).
* Tests are passing (mostly), as per previous comment.

Regarding compatibility:

* Kali 2.x ships with Ruby 2.1.5.
* Metasploit no longer requires Ruby 1.9.3, so the change to Ruby 2.x shouldn't affect the live CD, (except by making more work for @bw-z.)

Closing this issue.
